// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

// This test suite runs each operation test in parallel.
// Example, if your database has 3 tables, the suite will run:
// table1, table2 and table3 Delete in parallel
// table1, table2 and table3 Insert in parallel, and so forth.
// It does NOT run each operation group in parallel.
// Separating the tests thusly grants avoidance of Postgres deadlocks.
func TestParent(t *testing.T) {
	t.Run("DistanceAlerts", testDistanceAlerts)
	t.Run("DistanceData", testDistanceData)
	t.Run("MicrophoneAlerts", testMicrophoneAlerts)
	t.Run("MicrophoneData", testMicrophoneData)
	t.Run("MotionAlerts", testMotionAlerts)
	t.Run("MotionData", testMotionData)
	t.Run("PushTokens", testPushTokens)
}

func TestDelete(t *testing.T) {
	t.Run("DistanceAlerts", testDistanceAlertsDelete)
	t.Run("DistanceData", testDistanceDataDelete)
	t.Run("MicrophoneAlerts", testMicrophoneAlertsDelete)
	t.Run("MicrophoneData", testMicrophoneDataDelete)
	t.Run("MotionAlerts", testMotionAlertsDelete)
	t.Run("MotionData", testMotionDataDelete)
	t.Run("PushTokens", testPushTokensDelete)
}

func TestQueryDeleteAll(t *testing.T) {
	t.Run("DistanceAlerts", testDistanceAlertsQueryDeleteAll)
	t.Run("DistanceData", testDistanceDataQueryDeleteAll)
	t.Run("MicrophoneAlerts", testMicrophoneAlertsQueryDeleteAll)
	t.Run("MicrophoneData", testMicrophoneDataQueryDeleteAll)
	t.Run("MotionAlerts", testMotionAlertsQueryDeleteAll)
	t.Run("MotionData", testMotionDataQueryDeleteAll)
	t.Run("PushTokens", testPushTokensQueryDeleteAll)
}

func TestSliceDeleteAll(t *testing.T) {
	t.Run("DistanceAlerts", testDistanceAlertsSliceDeleteAll)
	t.Run("DistanceData", testDistanceDataSliceDeleteAll)
	t.Run("MicrophoneAlerts", testMicrophoneAlertsSliceDeleteAll)
	t.Run("MicrophoneData", testMicrophoneDataSliceDeleteAll)
	t.Run("MotionAlerts", testMotionAlertsSliceDeleteAll)
	t.Run("MotionData", testMotionDataSliceDeleteAll)
	t.Run("PushTokens", testPushTokensSliceDeleteAll)
}

func TestExists(t *testing.T) {
	t.Run("DistanceAlerts", testDistanceAlertsExists)
	t.Run("DistanceData", testDistanceDataExists)
	t.Run("MicrophoneAlerts", testMicrophoneAlertsExists)
	t.Run("MicrophoneData", testMicrophoneDataExists)
	t.Run("MotionAlerts", testMotionAlertsExists)
	t.Run("MotionData", testMotionDataExists)
	t.Run("PushTokens", testPushTokensExists)
}

func TestFind(t *testing.T) {
	t.Run("DistanceAlerts", testDistanceAlertsFind)
	t.Run("DistanceData", testDistanceDataFind)
	t.Run("MicrophoneAlerts", testMicrophoneAlertsFind)
	t.Run("MicrophoneData", testMicrophoneDataFind)
	t.Run("MotionAlerts", testMotionAlertsFind)
	t.Run("MotionData", testMotionDataFind)
	t.Run("PushTokens", testPushTokensFind)
}

func TestBind(t *testing.T) {
	t.Run("DistanceAlerts", testDistanceAlertsBind)
	t.Run("DistanceData", testDistanceDataBind)
	t.Run("MicrophoneAlerts", testMicrophoneAlertsBind)
	t.Run("MicrophoneData", testMicrophoneDataBind)
	t.Run("MotionAlerts", testMotionAlertsBind)
	t.Run("MotionData", testMotionDataBind)
	t.Run("PushTokens", testPushTokensBind)
}

func TestOne(t *testing.T) {
	t.Run("DistanceAlerts", testDistanceAlertsOne)
	t.Run("DistanceData", testDistanceDataOne)
	t.Run("MicrophoneAlerts", testMicrophoneAlertsOne)
	t.Run("MicrophoneData", testMicrophoneDataOne)
	t.Run("MotionAlerts", testMotionAlertsOne)
	t.Run("MotionData", testMotionDataOne)
	t.Run("PushTokens", testPushTokensOne)
}

func TestAll(t *testing.T) {
	t.Run("DistanceAlerts", testDistanceAlertsAll)
	t.Run("DistanceData", testDistanceDataAll)
	t.Run("MicrophoneAlerts", testMicrophoneAlertsAll)
	t.Run("MicrophoneData", testMicrophoneDataAll)
	t.Run("MotionAlerts", testMotionAlertsAll)
	t.Run("MotionData", testMotionDataAll)
	t.Run("PushTokens", testPushTokensAll)
}

func TestCount(t *testing.T) {
	t.Run("DistanceAlerts", testDistanceAlertsCount)
	t.Run("DistanceData", testDistanceDataCount)
	t.Run("MicrophoneAlerts", testMicrophoneAlertsCount)
	t.Run("MicrophoneData", testMicrophoneDataCount)
	t.Run("MotionAlerts", testMotionAlertsCount)
	t.Run("MotionData", testMotionDataCount)
	t.Run("PushTokens", testPushTokensCount)
}

func TestHooks(t *testing.T) {
	t.Run("DistanceAlerts", testDistanceAlertsHooks)
	t.Run("DistanceData", testDistanceDataHooks)
	t.Run("MicrophoneAlerts", testMicrophoneAlertsHooks)
	t.Run("MicrophoneData", testMicrophoneDataHooks)
	t.Run("MotionAlerts", testMotionAlertsHooks)
	t.Run("MotionData", testMotionDataHooks)
	t.Run("PushTokens", testPushTokensHooks)
}

func TestInsert(t *testing.T) {
	t.Run("DistanceAlerts", testDistanceAlertsInsert)
	t.Run("DistanceAlerts", testDistanceAlertsInsertWhitelist)
	t.Run("DistanceData", testDistanceDataInsert)
	t.Run("DistanceData", testDistanceDataInsertWhitelist)
	t.Run("MicrophoneAlerts", testMicrophoneAlertsInsert)
	t.Run("MicrophoneAlerts", testMicrophoneAlertsInsertWhitelist)
	t.Run("MicrophoneData", testMicrophoneDataInsert)
	t.Run("MicrophoneData", testMicrophoneDataInsertWhitelist)
	t.Run("MotionAlerts", testMotionAlertsInsert)
	t.Run("MotionAlerts", testMotionAlertsInsertWhitelist)
	t.Run("MotionData", testMotionDataInsert)
	t.Run("MotionData", testMotionDataInsertWhitelist)
	t.Run("PushTokens", testPushTokensInsert)
	t.Run("PushTokens", testPushTokensInsertWhitelist)
}

func TestReload(t *testing.T) {
	t.Run("DistanceAlerts", testDistanceAlertsReload)
	t.Run("DistanceData", testDistanceDataReload)
	t.Run("MicrophoneAlerts", testMicrophoneAlertsReload)
	t.Run("MicrophoneData", testMicrophoneDataReload)
	t.Run("MotionAlerts", testMotionAlertsReload)
	t.Run("MotionData", testMotionDataReload)
	t.Run("PushTokens", testPushTokensReload)
}

func TestReloadAll(t *testing.T) {
	t.Run("DistanceAlerts", testDistanceAlertsReloadAll)
	t.Run("DistanceData", testDistanceDataReloadAll)
	t.Run("MicrophoneAlerts", testMicrophoneAlertsReloadAll)
	t.Run("MicrophoneData", testMicrophoneDataReloadAll)
	t.Run("MotionAlerts", testMotionAlertsReloadAll)
	t.Run("MotionData", testMotionDataReloadAll)
	t.Run("PushTokens", testPushTokensReloadAll)
}

func TestSelect(t *testing.T) {
	t.Run("DistanceAlerts", testDistanceAlertsSelect)
	t.Run("DistanceData", testDistanceDataSelect)
	t.Run("MicrophoneAlerts", testMicrophoneAlertsSelect)
	t.Run("MicrophoneData", testMicrophoneDataSelect)
	t.Run("MotionAlerts", testMotionAlertsSelect)
	t.Run("MotionData", testMotionDataSelect)
	t.Run("PushTokens", testPushTokensSelect)
}

func TestUpdate(t *testing.T) {
	t.Run("DistanceAlerts", testDistanceAlertsUpdate)
	t.Run("DistanceData", testDistanceDataUpdate)
	t.Run("MicrophoneAlerts", testMicrophoneAlertsUpdate)
	t.Run("MicrophoneData", testMicrophoneDataUpdate)
	t.Run("MotionAlerts", testMotionAlertsUpdate)
	t.Run("MotionData", testMotionDataUpdate)
	t.Run("PushTokens", testPushTokensUpdate)
}

func TestSliceUpdateAll(t *testing.T) {
	t.Run("DistanceAlerts", testDistanceAlertsSliceUpdateAll)
	t.Run("DistanceData", testDistanceDataSliceUpdateAll)
	t.Run("MicrophoneAlerts", testMicrophoneAlertsSliceUpdateAll)
	t.Run("MicrophoneData", testMicrophoneDataSliceUpdateAll)
	t.Run("MotionAlerts", testMotionAlertsSliceUpdateAll)
	t.Run("MotionData", testMotionDataSliceUpdateAll)
	t.Run("PushTokens", testPushTokensSliceUpdateAll)
}
