// Code generated by SQLBoiler 4.17.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

// This test suite runs each operation test in parallel.
// Example, if your database has 3 tables, the suite will run:
// table1, table2 and table3 Delete in parallel
// table1, table2 and table3 Insert in parallel, and so forth.
// It does NOT run each operation group in parallel.
// Separating the tests thusly grants avoidance of Postgres deadlocks.
func TestParent(t *testing.T) {
	t.Run("GameTypes", testGameTypes)
	t.Run("Players", testPlayers)
	t.Run("Scores", testScores)
}

func TestDelete(t *testing.T) {
	t.Run("GameTypes", testGameTypesDelete)
	t.Run("Players", testPlayersDelete)
	t.Run("Scores", testScoresDelete)
}

func TestQueryDeleteAll(t *testing.T) {
	t.Run("GameTypes", testGameTypesQueryDeleteAll)
	t.Run("Players", testPlayersQueryDeleteAll)
	t.Run("Scores", testScoresQueryDeleteAll)
}

func TestSliceDeleteAll(t *testing.T) {
	t.Run("GameTypes", testGameTypesSliceDeleteAll)
	t.Run("Players", testPlayersSliceDeleteAll)
	t.Run("Scores", testScoresSliceDeleteAll)
}

func TestExists(t *testing.T) {
	t.Run("GameTypes", testGameTypesExists)
	t.Run("Players", testPlayersExists)
	t.Run("Scores", testScoresExists)
}

func TestFind(t *testing.T) {
	t.Run("GameTypes", testGameTypesFind)
	t.Run("Players", testPlayersFind)
	t.Run("Scores", testScoresFind)
}

func TestBind(t *testing.T) {
	t.Run("GameTypes", testGameTypesBind)
	t.Run("Players", testPlayersBind)
	t.Run("Scores", testScoresBind)
}

func TestOne(t *testing.T) {
	t.Run("GameTypes", testGameTypesOne)
	t.Run("Players", testPlayersOne)
	t.Run("Scores", testScoresOne)
}

func TestAll(t *testing.T) {
	t.Run("GameTypes", testGameTypesAll)
	t.Run("Players", testPlayersAll)
	t.Run("Scores", testScoresAll)
}

func TestCount(t *testing.T) {
	t.Run("GameTypes", testGameTypesCount)
	t.Run("Players", testPlayersCount)
	t.Run("Scores", testScoresCount)
}

func TestHooks(t *testing.T) {
	t.Run("GameTypes", testGameTypesHooks)
	t.Run("Players", testPlayersHooks)
	t.Run("Scores", testScoresHooks)
}

func TestInsert(t *testing.T) {
	t.Run("GameTypes", testGameTypesInsert)
	t.Run("GameTypes", testGameTypesInsertWhitelist)
	t.Run("Players", testPlayersInsert)
	t.Run("Players", testPlayersInsertWhitelist)
	t.Run("Scores", testScoresInsert)
	t.Run("Scores", testScoresInsertWhitelist)
}

func TestReload(t *testing.T) {
	t.Run("GameTypes", testGameTypesReload)
	t.Run("Players", testPlayersReload)
	t.Run("Scores", testScoresReload)
}

func TestReloadAll(t *testing.T) {
	t.Run("GameTypes", testGameTypesReloadAll)
	t.Run("Players", testPlayersReloadAll)
	t.Run("Scores", testScoresReloadAll)
}

func TestSelect(t *testing.T) {
	t.Run("GameTypes", testGameTypesSelect)
	t.Run("Players", testPlayersSelect)
	t.Run("Scores", testScoresSelect)
}

func TestUpdate(t *testing.T) {
	t.Run("GameTypes", testGameTypesUpdate)
	t.Run("Players", testPlayersUpdate)
	t.Run("Scores", testScoresUpdate)
}

func TestSliceUpdateAll(t *testing.T) {
	t.Run("GameTypes", testGameTypesSliceUpdateAll)
	t.Run("Players", testPlayersSliceUpdateAll)
	t.Run("Scores", testScoresSliceUpdateAll)
}
