// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/sqlboiler/v4/types"
	"github.com/volatiletech/strmangle"
)

// MicrophoneDatum is an object representing the database table.
type MicrophoneDatum struct {
	ID         int64         `boil:"id" json:"id" toml:"id" yaml:"id"`
	DeviceID   string        `boil:"device_id" json:"device_id" toml:"device_id" yaml:"device_id"`
	Decibels   types.Decimal `boil:"decibels" json:"decibels" toml:"decibels" yaml:"decibels"`
	RecordedAt null.Time     `boil:"recorded_at" json:"recorded_at,omitempty" toml:"recorded_at" yaml:"recorded_at,omitempty"`

	R *microphoneDatumR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L microphoneDatumL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var MicrophoneDatumColumns = struct {
	ID         string
	DeviceID   string
	Decibels   string
	RecordedAt string
}{
	ID:         "id",
	DeviceID:   "device_id",
	Decibels:   "decibels",
	RecordedAt: "recorded_at",
}

var MicrophoneDatumTableColumns = struct {
	ID         string
	DeviceID   string
	Decibels   string
	RecordedAt string
}{
	ID:         "microphone_data.id",
	DeviceID:   "microphone_data.device_id",
	Decibels:   "microphone_data.decibels",
	RecordedAt: "microphone_data.recorded_at",
}

// Generated where

var MicrophoneDatumWhere = struct {
	ID         whereHelperint64
	DeviceID   whereHelperstring
	Decibels   whereHelpertypes_Decimal
	RecordedAt whereHelpernull_Time
}{
	ID:         whereHelperint64{field: "\"microphone_data\".\"id\""},
	DeviceID:   whereHelperstring{field: "\"microphone_data\".\"device_id\""},
	Decibels:   whereHelpertypes_Decimal{field: "\"microphone_data\".\"decibels\""},
	RecordedAt: whereHelpernull_Time{field: "\"microphone_data\".\"recorded_at\""},
}

// MicrophoneDatumRels is where relationship names are stored.
var MicrophoneDatumRels = struct {
	DatumMicrophoneAlerts string
}{
	DatumMicrophoneAlerts: "DatumMicrophoneAlerts",
}

// microphoneDatumR is where relationships are stored.
type microphoneDatumR struct {
	DatumMicrophoneAlerts MicrophoneAlertSlice `boil:"DatumMicrophoneAlerts" json:"DatumMicrophoneAlerts" toml:"DatumMicrophoneAlerts" yaml:"DatumMicrophoneAlerts"`
}

// NewStruct creates a new relationship struct
func (*microphoneDatumR) NewStruct() *microphoneDatumR {
	return &microphoneDatumR{}
}

func (r *microphoneDatumR) GetDatumMicrophoneAlerts() MicrophoneAlertSlice {
	if r == nil {
		return nil
	}
	return r.DatumMicrophoneAlerts
}

// microphoneDatumL is where Load methods for each relationship are stored.
type microphoneDatumL struct{}

var (
	microphoneDatumAllColumns            = []string{"id", "device_id", "decibels", "recorded_at"}
	microphoneDatumColumnsWithoutDefault = []string{"device_id", "decibels"}
	microphoneDatumColumnsWithDefault    = []string{"id", "recorded_at"}
	microphoneDatumPrimaryKeyColumns     = []string{"id"}
	microphoneDatumGeneratedColumns      = []string{}
)

type (
	// MicrophoneDatumSlice is an alias for a slice of pointers to MicrophoneDatum.
	// This should almost always be used instead of []MicrophoneDatum.
	MicrophoneDatumSlice []*MicrophoneDatum
	// MicrophoneDatumHook is the signature for custom MicrophoneDatum hook methods
	MicrophoneDatumHook func(context.Context, boil.ContextExecutor, *MicrophoneDatum) error

	microphoneDatumQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	microphoneDatumType                 = reflect.TypeOf(&MicrophoneDatum{})
	microphoneDatumMapping              = queries.MakeStructMapping(microphoneDatumType)
	microphoneDatumPrimaryKeyMapping, _ = queries.BindMapping(microphoneDatumType, microphoneDatumMapping, microphoneDatumPrimaryKeyColumns)
	microphoneDatumInsertCacheMut       sync.RWMutex
	microphoneDatumInsertCache          = make(map[string]insertCache)
	microphoneDatumUpdateCacheMut       sync.RWMutex
	microphoneDatumUpdateCache          = make(map[string]updateCache)
	microphoneDatumUpsertCacheMut       sync.RWMutex
	microphoneDatumUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var microphoneDatumAfterSelectMu sync.Mutex
var microphoneDatumAfterSelectHooks []MicrophoneDatumHook

var microphoneDatumBeforeInsertMu sync.Mutex
var microphoneDatumBeforeInsertHooks []MicrophoneDatumHook
var microphoneDatumAfterInsertMu sync.Mutex
var microphoneDatumAfterInsertHooks []MicrophoneDatumHook

var microphoneDatumBeforeUpdateMu sync.Mutex
var microphoneDatumBeforeUpdateHooks []MicrophoneDatumHook
var microphoneDatumAfterUpdateMu sync.Mutex
var microphoneDatumAfterUpdateHooks []MicrophoneDatumHook

var microphoneDatumBeforeDeleteMu sync.Mutex
var microphoneDatumBeforeDeleteHooks []MicrophoneDatumHook
var microphoneDatumAfterDeleteMu sync.Mutex
var microphoneDatumAfterDeleteHooks []MicrophoneDatumHook

var microphoneDatumBeforeUpsertMu sync.Mutex
var microphoneDatumBeforeUpsertHooks []MicrophoneDatumHook
var microphoneDatumAfterUpsertMu sync.Mutex
var microphoneDatumAfterUpsertHooks []MicrophoneDatumHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *MicrophoneDatum) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range microphoneDatumAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *MicrophoneDatum) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range microphoneDatumBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *MicrophoneDatum) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range microphoneDatumAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *MicrophoneDatum) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range microphoneDatumBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *MicrophoneDatum) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range microphoneDatumAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *MicrophoneDatum) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range microphoneDatumBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *MicrophoneDatum) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range microphoneDatumAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *MicrophoneDatum) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range microphoneDatumBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *MicrophoneDatum) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range microphoneDatumAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddMicrophoneDatumHook registers your hook function for all future operations.
func AddMicrophoneDatumHook(hookPoint boil.HookPoint, microphoneDatumHook MicrophoneDatumHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		microphoneDatumAfterSelectMu.Lock()
		microphoneDatumAfterSelectHooks = append(microphoneDatumAfterSelectHooks, microphoneDatumHook)
		microphoneDatumAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		microphoneDatumBeforeInsertMu.Lock()
		microphoneDatumBeforeInsertHooks = append(microphoneDatumBeforeInsertHooks, microphoneDatumHook)
		microphoneDatumBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		microphoneDatumAfterInsertMu.Lock()
		microphoneDatumAfterInsertHooks = append(microphoneDatumAfterInsertHooks, microphoneDatumHook)
		microphoneDatumAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		microphoneDatumBeforeUpdateMu.Lock()
		microphoneDatumBeforeUpdateHooks = append(microphoneDatumBeforeUpdateHooks, microphoneDatumHook)
		microphoneDatumBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		microphoneDatumAfterUpdateMu.Lock()
		microphoneDatumAfterUpdateHooks = append(microphoneDatumAfterUpdateHooks, microphoneDatumHook)
		microphoneDatumAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		microphoneDatumBeforeDeleteMu.Lock()
		microphoneDatumBeforeDeleteHooks = append(microphoneDatumBeforeDeleteHooks, microphoneDatumHook)
		microphoneDatumBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		microphoneDatumAfterDeleteMu.Lock()
		microphoneDatumAfterDeleteHooks = append(microphoneDatumAfterDeleteHooks, microphoneDatumHook)
		microphoneDatumAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		microphoneDatumBeforeUpsertMu.Lock()
		microphoneDatumBeforeUpsertHooks = append(microphoneDatumBeforeUpsertHooks, microphoneDatumHook)
		microphoneDatumBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		microphoneDatumAfterUpsertMu.Lock()
		microphoneDatumAfterUpsertHooks = append(microphoneDatumAfterUpsertHooks, microphoneDatumHook)
		microphoneDatumAfterUpsertMu.Unlock()
	}
}

// One returns a single microphoneDatum record from the query.
func (q microphoneDatumQuery) One(ctx context.Context, exec boil.ContextExecutor) (*MicrophoneDatum, error) {
	o := &MicrophoneDatum{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for microphone_data")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all MicrophoneDatum records from the query.
func (q microphoneDatumQuery) All(ctx context.Context, exec boil.ContextExecutor) (MicrophoneDatumSlice, error) {
	var o []*MicrophoneDatum

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to MicrophoneDatum slice")
	}

	if len(microphoneDatumAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all MicrophoneDatum records in the query.
func (q microphoneDatumQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count microphone_data rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q microphoneDatumQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if microphone_data exists")
	}

	return count > 0, nil
}

// DatumMicrophoneAlerts retrieves all the microphone_alert's MicrophoneAlerts with an executor via data_id column.
func (o *MicrophoneDatum) DatumMicrophoneAlerts(mods ...qm.QueryMod) microphoneAlertQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"microphone_alerts\".\"data_id\"=?", o.ID),
	)

	return MicrophoneAlerts(queryMods...)
}

// LoadDatumMicrophoneAlerts allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (microphoneDatumL) LoadDatumMicrophoneAlerts(ctx context.Context, e boil.ContextExecutor, singular bool, maybeMicrophoneDatum interface{}, mods queries.Applicator) error {
	var slice []*MicrophoneDatum
	var object *MicrophoneDatum

	if singular {
		var ok bool
		object, ok = maybeMicrophoneDatum.(*MicrophoneDatum)
		if !ok {
			object = new(MicrophoneDatum)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeMicrophoneDatum)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeMicrophoneDatum))
			}
		}
	} else {
		s, ok := maybeMicrophoneDatum.(*[]*MicrophoneDatum)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeMicrophoneDatum)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeMicrophoneDatum))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &microphoneDatumR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &microphoneDatumR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`microphone_alerts`),
		qm.WhereIn(`microphone_alerts.data_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load microphone_alerts")
	}

	var resultSlice []*MicrophoneAlert
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice microphone_alerts")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on microphone_alerts")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for microphone_alerts")
	}

	if len(microphoneAlertAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.DatumMicrophoneAlerts = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &microphoneAlertR{}
			}
			foreign.R.Datum = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.ID, foreign.DataID) {
				local.R.DatumMicrophoneAlerts = append(local.R.DatumMicrophoneAlerts, foreign)
				if foreign.R == nil {
					foreign.R = &microphoneAlertR{}
				}
				foreign.R.Datum = local
				break
			}
		}
	}

	return nil
}

// AddDatumMicrophoneAlerts adds the given related objects to the existing relationships
// of the microphone_datum, optionally inserting them as new records.
// Appends related to o.R.DatumMicrophoneAlerts.
// Sets related.R.Datum appropriately.
func (o *MicrophoneDatum) AddDatumMicrophoneAlerts(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*MicrophoneAlert) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.DataID, o.ID)
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"microphone_alerts\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"data_id"}),
				strmangle.WhereClause("\"", "\"", 2, microphoneAlertPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.DataID, o.ID)
		}
	}

	if o.R == nil {
		o.R = &microphoneDatumR{
			DatumMicrophoneAlerts: related,
		}
	} else {
		o.R.DatumMicrophoneAlerts = append(o.R.DatumMicrophoneAlerts, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &microphoneAlertR{
				Datum: o,
			}
		} else {
			rel.R.Datum = o
		}
	}
	return nil
}

// SetDatumMicrophoneAlerts removes all previously related items of the
// microphone_datum replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.Datum's DatumMicrophoneAlerts accordingly.
// Replaces o.R.DatumMicrophoneAlerts with related.
// Sets related.R.Datum's DatumMicrophoneAlerts accordingly.
func (o *MicrophoneDatum) SetDatumMicrophoneAlerts(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*MicrophoneAlert) error {
	query := "update \"microphone_alerts\" set \"data_id\" = null where \"data_id\" = $1"
	values := []interface{}{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.DatumMicrophoneAlerts {
			queries.SetScanner(&rel.DataID, nil)
			if rel.R == nil {
				continue
			}

			rel.R.Datum = nil
		}
		o.R.DatumMicrophoneAlerts = nil
	}

	return o.AddDatumMicrophoneAlerts(ctx, exec, insert, related...)
}

// RemoveDatumMicrophoneAlerts relationships from objects passed in.
// Removes related items from R.DatumMicrophoneAlerts (uses pointer comparison, removal does not keep order)
// Sets related.R.Datum.
func (o *MicrophoneDatum) RemoveDatumMicrophoneAlerts(ctx context.Context, exec boil.ContextExecutor, related ...*MicrophoneAlert) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.DataID, nil)
		if rel.R != nil {
			rel.R.Datum = nil
		}
		if _, err = rel.Update(ctx, exec, boil.Whitelist("data_id")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.DatumMicrophoneAlerts {
			if rel != ri {
				continue
			}

			ln := len(o.R.DatumMicrophoneAlerts)
			if ln > 1 && i < ln-1 {
				o.R.DatumMicrophoneAlerts[i] = o.R.DatumMicrophoneAlerts[ln-1]
			}
			o.R.DatumMicrophoneAlerts = o.R.DatumMicrophoneAlerts[:ln-1]
			break
		}
	}

	return nil
}

// MicrophoneData retrieves all the records using an executor.
func MicrophoneData(mods ...qm.QueryMod) microphoneDatumQuery {
	mods = append(mods, qm.From("\"microphone_data\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"microphone_data\".*"})
	}

	return microphoneDatumQuery{q}
}

// FindMicrophoneDatum retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindMicrophoneDatum(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*MicrophoneDatum, error) {
	microphoneDatumObj := &MicrophoneDatum{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"microphone_data\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, microphoneDatumObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from microphone_data")
	}

	if err = microphoneDatumObj.doAfterSelectHooks(ctx, exec); err != nil {
		return microphoneDatumObj, err
	}

	return microphoneDatumObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *MicrophoneDatum) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no microphone_data provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(microphoneDatumColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	microphoneDatumInsertCacheMut.RLock()
	cache, cached := microphoneDatumInsertCache[key]
	microphoneDatumInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			microphoneDatumAllColumns,
			microphoneDatumColumnsWithDefault,
			microphoneDatumColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(microphoneDatumType, microphoneDatumMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(microphoneDatumType, microphoneDatumMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"microphone_data\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"microphone_data\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into microphone_data")
	}

	if !cached {
		microphoneDatumInsertCacheMut.Lock()
		microphoneDatumInsertCache[key] = cache
		microphoneDatumInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the MicrophoneDatum.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *MicrophoneDatum) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	microphoneDatumUpdateCacheMut.RLock()
	cache, cached := microphoneDatumUpdateCache[key]
	microphoneDatumUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			microphoneDatumAllColumns,
			microphoneDatumPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update microphone_data, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"microphone_data\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, microphoneDatumPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(microphoneDatumType, microphoneDatumMapping, append(wl, microphoneDatumPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update microphone_data row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for microphone_data")
	}

	if !cached {
		microphoneDatumUpdateCacheMut.Lock()
		microphoneDatumUpdateCache[key] = cache
		microphoneDatumUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q microphoneDatumQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for microphone_data")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for microphone_data")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o MicrophoneDatumSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), microphoneDatumPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"microphone_data\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, microphoneDatumPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in microphoneDatum slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all microphoneDatum")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *MicrophoneDatum) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no microphone_data provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(microphoneDatumColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	microphoneDatumUpsertCacheMut.RLock()
	cache, cached := microphoneDatumUpsertCache[key]
	microphoneDatumUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			microphoneDatumAllColumns,
			microphoneDatumColumnsWithDefault,
			microphoneDatumColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			microphoneDatumAllColumns,
			microphoneDatumPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert microphone_data, could not build update column list")
		}

		ret := strmangle.SetComplement(microphoneDatumAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(microphoneDatumPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert microphone_data, could not build conflict column list")
			}

			conflict = make([]string, len(microphoneDatumPrimaryKeyColumns))
			copy(conflict, microphoneDatumPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"microphone_data\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(microphoneDatumType, microphoneDatumMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(microphoneDatumType, microphoneDatumMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert microphone_data")
	}

	if !cached {
		microphoneDatumUpsertCacheMut.Lock()
		microphoneDatumUpsertCache[key] = cache
		microphoneDatumUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single MicrophoneDatum record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *MicrophoneDatum) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no MicrophoneDatum provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), microphoneDatumPrimaryKeyMapping)
	sql := "DELETE FROM \"microphone_data\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from microphone_data")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for microphone_data")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q microphoneDatumQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no microphoneDatumQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from microphone_data")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for microphone_data")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o MicrophoneDatumSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(microphoneDatumBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), microphoneDatumPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"microphone_data\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, microphoneDatumPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from microphoneDatum slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for microphone_data")
	}

	if len(microphoneDatumAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *MicrophoneDatum) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindMicrophoneDatum(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *MicrophoneDatumSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := MicrophoneDatumSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), microphoneDatumPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"microphone_data\".* FROM \"microphone_data\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, microphoneDatumPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in MicrophoneDatumSlice")
	}

	*o = slice

	return nil
}

// MicrophoneDatumExists checks if the MicrophoneDatum row exists.
func MicrophoneDatumExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"microphone_data\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if microphone_data exists")
	}

	return exists, nil
}

// Exists checks if the MicrophoneDatum row exists.
func (o *MicrophoneDatum) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return MicrophoneDatumExists(ctx, exec, o.ID)
}
