// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/sqlboiler/v4/types"
	"github.com/volatiletech/strmangle"
)

// MicrophoneAlert is an object representing the database table.
type MicrophoneAlert struct {
	ID                int64         `boil:"id" json:"id" toml:"id" yaml:"id"`
	DeviceID          string        `boil:"device_id" json:"device_id" toml:"device_id" yaml:"device_id"`
	DataID            null.Int64    `boil:"data_id" json:"data_id,omitempty" toml:"data_id" yaml:"data_id,omitempty"`
	Decibels          types.Decimal `boil:"decibels" json:"decibels" toml:"decibels" yaml:"decibels"`
	ThresholdExceeded types.Decimal `boil:"threshold_exceeded" json:"threshold_exceeded" toml:"threshold_exceeded" yaml:"threshold_exceeded"`
	AlertStatus       null.String   `boil:"alert_status" json:"alert_status,omitempty" toml:"alert_status" yaml:"alert_status,omitempty"`
	AcknowledgedAt    null.Time     `boil:"acknowledged_at" json:"acknowledged_at,omitempty" toml:"acknowledged_at" yaml:"acknowledged_at,omitempty"`
	ResolvedAt        null.Time     `boil:"resolved_at" json:"resolved_at,omitempty" toml:"resolved_at" yaml:"resolved_at,omitempty"`
	CreatedAt         null.Time     `boil:"created_at" json:"created_at,omitempty" toml:"created_at" yaml:"created_at,omitempty"`

	R *microphoneAlertR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L microphoneAlertL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var MicrophoneAlertColumns = struct {
	ID                string
	DeviceID          string
	DataID            string
	Decibels          string
	ThresholdExceeded string
	AlertStatus       string
	AcknowledgedAt    string
	ResolvedAt        string
	CreatedAt         string
}{
	ID:                "id",
	DeviceID:          "device_id",
	DataID:            "data_id",
	Decibels:          "decibels",
	ThresholdExceeded: "threshold_exceeded",
	AlertStatus:       "alert_status",
	AcknowledgedAt:    "acknowledged_at",
	ResolvedAt:        "resolved_at",
	CreatedAt:         "created_at",
}

var MicrophoneAlertTableColumns = struct {
	ID                string
	DeviceID          string
	DataID            string
	Decibels          string
	ThresholdExceeded string
	AlertStatus       string
	AcknowledgedAt    string
	ResolvedAt        string
	CreatedAt         string
}{
	ID:                "microphone_alerts.id",
	DeviceID:          "microphone_alerts.device_id",
	DataID:            "microphone_alerts.data_id",
	Decibels:          "microphone_alerts.decibels",
	ThresholdExceeded: "microphone_alerts.threshold_exceeded",
	AlertStatus:       "microphone_alerts.alert_status",
	AcknowledgedAt:    "microphone_alerts.acknowledged_at",
	ResolvedAt:        "microphone_alerts.resolved_at",
	CreatedAt:         "microphone_alerts.created_at",
}

// Generated where

var MicrophoneAlertWhere = struct {
	ID                whereHelperint64
	DeviceID          whereHelperstring
	DataID            whereHelpernull_Int64
	Decibels          whereHelpertypes_Decimal
	ThresholdExceeded whereHelpertypes_Decimal
	AlertStatus       whereHelpernull_String
	AcknowledgedAt    whereHelpernull_Time
	ResolvedAt        whereHelpernull_Time
	CreatedAt         whereHelpernull_Time
}{
	ID:                whereHelperint64{field: "\"microphone_alerts\".\"id\""},
	DeviceID:          whereHelperstring{field: "\"microphone_alerts\".\"device_id\""},
	DataID:            whereHelpernull_Int64{field: "\"microphone_alerts\".\"data_id\""},
	Decibels:          whereHelpertypes_Decimal{field: "\"microphone_alerts\".\"decibels\""},
	ThresholdExceeded: whereHelpertypes_Decimal{field: "\"microphone_alerts\".\"threshold_exceeded\""},
	AlertStatus:       whereHelpernull_String{field: "\"microphone_alerts\".\"alert_status\""},
	AcknowledgedAt:    whereHelpernull_Time{field: "\"microphone_alerts\".\"acknowledged_at\""},
	ResolvedAt:        whereHelpernull_Time{field: "\"microphone_alerts\".\"resolved_at\""},
	CreatedAt:         whereHelpernull_Time{field: "\"microphone_alerts\".\"created_at\""},
}

// MicrophoneAlertRels is where relationship names are stored.
var MicrophoneAlertRels = struct {
	Datum string
}{
	Datum: "Datum",
}

// microphoneAlertR is where relationships are stored.
type microphoneAlertR struct {
	Datum *MicrophoneDatum `boil:"Datum" json:"Datum" toml:"Datum" yaml:"Datum"`
}

// NewStruct creates a new relationship struct
func (*microphoneAlertR) NewStruct() *microphoneAlertR {
	return &microphoneAlertR{}
}

func (r *microphoneAlertR) GetDatum() *MicrophoneDatum {
	if r == nil {
		return nil
	}
	return r.Datum
}

// microphoneAlertL is where Load methods for each relationship are stored.
type microphoneAlertL struct{}

var (
	microphoneAlertAllColumns            = []string{"id", "device_id", "data_id", "decibels", "threshold_exceeded", "alert_status", "acknowledged_at", "resolved_at", "created_at"}
	microphoneAlertColumnsWithoutDefault = []string{"device_id", "decibels", "threshold_exceeded"}
	microphoneAlertColumnsWithDefault    = []string{"id", "data_id", "alert_status", "acknowledged_at", "resolved_at", "created_at"}
	microphoneAlertPrimaryKeyColumns     = []string{"id"}
	microphoneAlertGeneratedColumns      = []string{}
)

type (
	// MicrophoneAlertSlice is an alias for a slice of pointers to MicrophoneAlert.
	// This should almost always be used instead of []MicrophoneAlert.
	MicrophoneAlertSlice []*MicrophoneAlert
	// MicrophoneAlertHook is the signature for custom MicrophoneAlert hook methods
	MicrophoneAlertHook func(context.Context, boil.ContextExecutor, *MicrophoneAlert) error

	microphoneAlertQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	microphoneAlertType                 = reflect.TypeOf(&MicrophoneAlert{})
	microphoneAlertMapping              = queries.MakeStructMapping(microphoneAlertType)
	microphoneAlertPrimaryKeyMapping, _ = queries.BindMapping(microphoneAlertType, microphoneAlertMapping, microphoneAlertPrimaryKeyColumns)
	microphoneAlertInsertCacheMut       sync.RWMutex
	microphoneAlertInsertCache          = make(map[string]insertCache)
	microphoneAlertUpdateCacheMut       sync.RWMutex
	microphoneAlertUpdateCache          = make(map[string]updateCache)
	microphoneAlertUpsertCacheMut       sync.RWMutex
	microphoneAlertUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var microphoneAlertAfterSelectMu sync.Mutex
var microphoneAlertAfterSelectHooks []MicrophoneAlertHook

var microphoneAlertBeforeInsertMu sync.Mutex
var microphoneAlertBeforeInsertHooks []MicrophoneAlertHook
var microphoneAlertAfterInsertMu sync.Mutex
var microphoneAlertAfterInsertHooks []MicrophoneAlertHook

var microphoneAlertBeforeUpdateMu sync.Mutex
var microphoneAlertBeforeUpdateHooks []MicrophoneAlertHook
var microphoneAlertAfterUpdateMu sync.Mutex
var microphoneAlertAfterUpdateHooks []MicrophoneAlertHook

var microphoneAlertBeforeDeleteMu sync.Mutex
var microphoneAlertBeforeDeleteHooks []MicrophoneAlertHook
var microphoneAlertAfterDeleteMu sync.Mutex
var microphoneAlertAfterDeleteHooks []MicrophoneAlertHook

var microphoneAlertBeforeUpsertMu sync.Mutex
var microphoneAlertBeforeUpsertHooks []MicrophoneAlertHook
var microphoneAlertAfterUpsertMu sync.Mutex
var microphoneAlertAfterUpsertHooks []MicrophoneAlertHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *MicrophoneAlert) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range microphoneAlertAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *MicrophoneAlert) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range microphoneAlertBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *MicrophoneAlert) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range microphoneAlertAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *MicrophoneAlert) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range microphoneAlertBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *MicrophoneAlert) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range microphoneAlertAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *MicrophoneAlert) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range microphoneAlertBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *MicrophoneAlert) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range microphoneAlertAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *MicrophoneAlert) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range microphoneAlertBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *MicrophoneAlert) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range microphoneAlertAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddMicrophoneAlertHook registers your hook function for all future operations.
func AddMicrophoneAlertHook(hookPoint boil.HookPoint, microphoneAlertHook MicrophoneAlertHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		microphoneAlertAfterSelectMu.Lock()
		microphoneAlertAfterSelectHooks = append(microphoneAlertAfterSelectHooks, microphoneAlertHook)
		microphoneAlertAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		microphoneAlertBeforeInsertMu.Lock()
		microphoneAlertBeforeInsertHooks = append(microphoneAlertBeforeInsertHooks, microphoneAlertHook)
		microphoneAlertBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		microphoneAlertAfterInsertMu.Lock()
		microphoneAlertAfterInsertHooks = append(microphoneAlertAfterInsertHooks, microphoneAlertHook)
		microphoneAlertAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		microphoneAlertBeforeUpdateMu.Lock()
		microphoneAlertBeforeUpdateHooks = append(microphoneAlertBeforeUpdateHooks, microphoneAlertHook)
		microphoneAlertBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		microphoneAlertAfterUpdateMu.Lock()
		microphoneAlertAfterUpdateHooks = append(microphoneAlertAfterUpdateHooks, microphoneAlertHook)
		microphoneAlertAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		microphoneAlertBeforeDeleteMu.Lock()
		microphoneAlertBeforeDeleteHooks = append(microphoneAlertBeforeDeleteHooks, microphoneAlertHook)
		microphoneAlertBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		microphoneAlertAfterDeleteMu.Lock()
		microphoneAlertAfterDeleteHooks = append(microphoneAlertAfterDeleteHooks, microphoneAlertHook)
		microphoneAlertAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		microphoneAlertBeforeUpsertMu.Lock()
		microphoneAlertBeforeUpsertHooks = append(microphoneAlertBeforeUpsertHooks, microphoneAlertHook)
		microphoneAlertBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		microphoneAlertAfterUpsertMu.Lock()
		microphoneAlertAfterUpsertHooks = append(microphoneAlertAfterUpsertHooks, microphoneAlertHook)
		microphoneAlertAfterUpsertMu.Unlock()
	}
}

// One returns a single microphoneAlert record from the query.
func (q microphoneAlertQuery) One(ctx context.Context, exec boil.ContextExecutor) (*MicrophoneAlert, error) {
	o := &MicrophoneAlert{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for microphone_alerts")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all MicrophoneAlert records from the query.
func (q microphoneAlertQuery) All(ctx context.Context, exec boil.ContextExecutor) (MicrophoneAlertSlice, error) {
	var o []*MicrophoneAlert

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to MicrophoneAlert slice")
	}

	if len(microphoneAlertAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all MicrophoneAlert records in the query.
func (q microphoneAlertQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count microphone_alerts rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q microphoneAlertQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if microphone_alerts exists")
	}

	return count > 0, nil
}

// Datum pointed to by the foreign key.
func (o *MicrophoneAlert) Datum(mods ...qm.QueryMod) microphoneDatumQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.DataID),
	}

	queryMods = append(queryMods, mods...)

	return MicrophoneData(queryMods...)
}

// LoadDatum allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (microphoneAlertL) LoadDatum(ctx context.Context, e boil.ContextExecutor, singular bool, maybeMicrophoneAlert interface{}, mods queries.Applicator) error {
	var slice []*MicrophoneAlert
	var object *MicrophoneAlert

	if singular {
		var ok bool
		object, ok = maybeMicrophoneAlert.(*MicrophoneAlert)
		if !ok {
			object = new(MicrophoneAlert)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeMicrophoneAlert)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeMicrophoneAlert))
			}
		}
	} else {
		s, ok := maybeMicrophoneAlert.(*[]*MicrophoneAlert)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeMicrophoneAlert)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeMicrophoneAlert))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &microphoneAlertR{}
		}
		if !queries.IsNil(object.DataID) {
			args[object.DataID] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &microphoneAlertR{}
			}

			if !queries.IsNil(obj.DataID) {
				args[obj.DataID] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`microphone_data`),
		qm.WhereIn(`microphone_data.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load MicrophoneDatum")
	}

	var resultSlice []*MicrophoneDatum
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice MicrophoneDatum")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for microphone_data")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for microphone_data")
	}

	if len(microphoneDatumAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Datum = foreign
		if foreign.R == nil {
			foreign.R = &microphoneDatumR{}
		}
		foreign.R.DatumMicrophoneAlerts = append(foreign.R.DatumMicrophoneAlerts, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.DataID, foreign.ID) {
				local.R.Datum = foreign
				if foreign.R == nil {
					foreign.R = &microphoneDatumR{}
				}
				foreign.R.DatumMicrophoneAlerts = append(foreign.R.DatumMicrophoneAlerts, local)
				break
			}
		}
	}

	return nil
}

// SetDatum of the microphoneAlert to the related item.
// Sets o.R.Datum to related.
// Adds o to related.R.DatumMicrophoneAlerts.
func (o *MicrophoneAlert) SetDatum(ctx context.Context, exec boil.ContextExecutor, insert bool, related *MicrophoneDatum) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"microphone_alerts\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"data_id"}),
		strmangle.WhereClause("\"", "\"", 2, microphoneAlertPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.DataID, related.ID)
	if o.R == nil {
		o.R = &microphoneAlertR{
			Datum: related,
		}
	} else {
		o.R.Datum = related
	}

	if related.R == nil {
		related.R = &microphoneDatumR{
			DatumMicrophoneAlerts: MicrophoneAlertSlice{o},
		}
	} else {
		related.R.DatumMicrophoneAlerts = append(related.R.DatumMicrophoneAlerts, o)
	}

	return nil
}

// RemoveDatum relationship.
// Sets o.R.Datum to nil.
// Removes o from all passed in related items' relationships struct.
func (o *MicrophoneAlert) RemoveDatum(ctx context.Context, exec boil.ContextExecutor, related *MicrophoneDatum) error {
	var err error

	queries.SetScanner(&o.DataID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("data_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.Datum = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.DatumMicrophoneAlerts {
		if queries.Equal(o.DataID, ri.DataID) {
			continue
		}

		ln := len(related.R.DatumMicrophoneAlerts)
		if ln > 1 && i < ln-1 {
			related.R.DatumMicrophoneAlerts[i] = related.R.DatumMicrophoneAlerts[ln-1]
		}
		related.R.DatumMicrophoneAlerts = related.R.DatumMicrophoneAlerts[:ln-1]
		break
	}
	return nil
}

// MicrophoneAlerts retrieves all the records using an executor.
func MicrophoneAlerts(mods ...qm.QueryMod) microphoneAlertQuery {
	mods = append(mods, qm.From("\"microphone_alerts\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"microphone_alerts\".*"})
	}

	return microphoneAlertQuery{q}
}

// FindMicrophoneAlert retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindMicrophoneAlert(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*MicrophoneAlert, error) {
	microphoneAlertObj := &MicrophoneAlert{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"microphone_alerts\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, microphoneAlertObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from microphone_alerts")
	}

	if err = microphoneAlertObj.doAfterSelectHooks(ctx, exec); err != nil {
		return microphoneAlertObj, err
	}

	return microphoneAlertObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *MicrophoneAlert) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no microphone_alerts provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(microphoneAlertColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	microphoneAlertInsertCacheMut.RLock()
	cache, cached := microphoneAlertInsertCache[key]
	microphoneAlertInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			microphoneAlertAllColumns,
			microphoneAlertColumnsWithDefault,
			microphoneAlertColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(microphoneAlertType, microphoneAlertMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(microphoneAlertType, microphoneAlertMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"microphone_alerts\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"microphone_alerts\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into microphone_alerts")
	}

	if !cached {
		microphoneAlertInsertCacheMut.Lock()
		microphoneAlertInsertCache[key] = cache
		microphoneAlertInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the MicrophoneAlert.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *MicrophoneAlert) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	microphoneAlertUpdateCacheMut.RLock()
	cache, cached := microphoneAlertUpdateCache[key]
	microphoneAlertUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			microphoneAlertAllColumns,
			microphoneAlertPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update microphone_alerts, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"microphone_alerts\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, microphoneAlertPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(microphoneAlertType, microphoneAlertMapping, append(wl, microphoneAlertPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update microphone_alerts row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for microphone_alerts")
	}

	if !cached {
		microphoneAlertUpdateCacheMut.Lock()
		microphoneAlertUpdateCache[key] = cache
		microphoneAlertUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q microphoneAlertQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for microphone_alerts")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for microphone_alerts")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o MicrophoneAlertSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), microphoneAlertPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"microphone_alerts\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, microphoneAlertPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in microphoneAlert slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all microphoneAlert")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *MicrophoneAlert) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no microphone_alerts provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(microphoneAlertColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	microphoneAlertUpsertCacheMut.RLock()
	cache, cached := microphoneAlertUpsertCache[key]
	microphoneAlertUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			microphoneAlertAllColumns,
			microphoneAlertColumnsWithDefault,
			microphoneAlertColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			microphoneAlertAllColumns,
			microphoneAlertPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert microphone_alerts, could not build update column list")
		}

		ret := strmangle.SetComplement(microphoneAlertAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(microphoneAlertPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert microphone_alerts, could not build conflict column list")
			}

			conflict = make([]string, len(microphoneAlertPrimaryKeyColumns))
			copy(conflict, microphoneAlertPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"microphone_alerts\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(microphoneAlertType, microphoneAlertMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(microphoneAlertType, microphoneAlertMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert microphone_alerts")
	}

	if !cached {
		microphoneAlertUpsertCacheMut.Lock()
		microphoneAlertUpsertCache[key] = cache
		microphoneAlertUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single MicrophoneAlert record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *MicrophoneAlert) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no MicrophoneAlert provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), microphoneAlertPrimaryKeyMapping)
	sql := "DELETE FROM \"microphone_alerts\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from microphone_alerts")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for microphone_alerts")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q microphoneAlertQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no microphoneAlertQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from microphone_alerts")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for microphone_alerts")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o MicrophoneAlertSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(microphoneAlertBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), microphoneAlertPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"microphone_alerts\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, microphoneAlertPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from microphoneAlert slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for microphone_alerts")
	}

	if len(microphoneAlertAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *MicrophoneAlert) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindMicrophoneAlert(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *MicrophoneAlertSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := MicrophoneAlertSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), microphoneAlertPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"microphone_alerts\".* FROM \"microphone_alerts\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, microphoneAlertPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in MicrophoneAlertSlice")
	}

	*o = slice

	return nil
}

// MicrophoneAlertExists checks if the MicrophoneAlert row exists.
func MicrophoneAlertExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"microphone_alerts\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if microphone_alerts exists")
	}

	return exists, nil
}

// Exists checks if the MicrophoneAlert row exists.
func (o *MicrophoneAlert) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return MicrophoneAlertExists(ctx, exec, o.ID)
}
