// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testMicrophoneData(t *testing.T) {
	t.Parallel()

	query := MicrophoneData()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testMicrophoneDataDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MicrophoneDatum{}
	if err = randomize.Struct(seed, o, microphoneDatumDBTypes, true, microphoneDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MicrophoneDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := MicrophoneData().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testMicrophoneDataQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MicrophoneDatum{}
	if err = randomize.Struct(seed, o, microphoneDatumDBTypes, true, microphoneDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MicrophoneDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := MicrophoneData().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := MicrophoneData().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testMicrophoneDataSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MicrophoneDatum{}
	if err = randomize.Struct(seed, o, microphoneDatumDBTypes, true, microphoneDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MicrophoneDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := MicrophoneDatumSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := MicrophoneData().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testMicrophoneDataExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MicrophoneDatum{}
	if err = randomize.Struct(seed, o, microphoneDatumDBTypes, true, microphoneDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MicrophoneDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := MicrophoneDatumExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if MicrophoneDatum exists: %s", err)
	}
	if !e {
		t.Errorf("Expected MicrophoneDatumExists to return true, but got false.")
	}
}

func testMicrophoneDataFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MicrophoneDatum{}
	if err = randomize.Struct(seed, o, microphoneDatumDBTypes, true, microphoneDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MicrophoneDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	microphoneDatumFound, err := FindMicrophoneDatum(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if microphoneDatumFound == nil {
		t.Error("want a record, got nil")
	}
}

func testMicrophoneDataBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MicrophoneDatum{}
	if err = randomize.Struct(seed, o, microphoneDatumDBTypes, true, microphoneDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MicrophoneDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = MicrophoneData().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testMicrophoneDataOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MicrophoneDatum{}
	if err = randomize.Struct(seed, o, microphoneDatumDBTypes, true, microphoneDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MicrophoneDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := MicrophoneData().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testMicrophoneDataAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	microphoneDatumOne := &MicrophoneDatum{}
	microphoneDatumTwo := &MicrophoneDatum{}
	if err = randomize.Struct(seed, microphoneDatumOne, microphoneDatumDBTypes, false, microphoneDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MicrophoneDatum struct: %s", err)
	}
	if err = randomize.Struct(seed, microphoneDatumTwo, microphoneDatumDBTypes, false, microphoneDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MicrophoneDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = microphoneDatumOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = microphoneDatumTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := MicrophoneData().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testMicrophoneDataCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	microphoneDatumOne := &MicrophoneDatum{}
	microphoneDatumTwo := &MicrophoneDatum{}
	if err = randomize.Struct(seed, microphoneDatumOne, microphoneDatumDBTypes, false, microphoneDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MicrophoneDatum struct: %s", err)
	}
	if err = randomize.Struct(seed, microphoneDatumTwo, microphoneDatumDBTypes, false, microphoneDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MicrophoneDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = microphoneDatumOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = microphoneDatumTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := MicrophoneData().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func microphoneDatumBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *MicrophoneDatum) error {
	*o = MicrophoneDatum{}
	return nil
}

func microphoneDatumAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *MicrophoneDatum) error {
	*o = MicrophoneDatum{}
	return nil
}

func microphoneDatumAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *MicrophoneDatum) error {
	*o = MicrophoneDatum{}
	return nil
}

func microphoneDatumBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *MicrophoneDatum) error {
	*o = MicrophoneDatum{}
	return nil
}

func microphoneDatumAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *MicrophoneDatum) error {
	*o = MicrophoneDatum{}
	return nil
}

func microphoneDatumBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *MicrophoneDatum) error {
	*o = MicrophoneDatum{}
	return nil
}

func microphoneDatumAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *MicrophoneDatum) error {
	*o = MicrophoneDatum{}
	return nil
}

func microphoneDatumBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *MicrophoneDatum) error {
	*o = MicrophoneDatum{}
	return nil
}

func microphoneDatumAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *MicrophoneDatum) error {
	*o = MicrophoneDatum{}
	return nil
}

func testMicrophoneDataHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &MicrophoneDatum{}
	o := &MicrophoneDatum{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, microphoneDatumDBTypes, false); err != nil {
		t.Errorf("Unable to randomize MicrophoneDatum object: %s", err)
	}

	AddMicrophoneDatumHook(boil.BeforeInsertHook, microphoneDatumBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	microphoneDatumBeforeInsertHooks = []MicrophoneDatumHook{}

	AddMicrophoneDatumHook(boil.AfterInsertHook, microphoneDatumAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	microphoneDatumAfterInsertHooks = []MicrophoneDatumHook{}

	AddMicrophoneDatumHook(boil.AfterSelectHook, microphoneDatumAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	microphoneDatumAfterSelectHooks = []MicrophoneDatumHook{}

	AddMicrophoneDatumHook(boil.BeforeUpdateHook, microphoneDatumBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	microphoneDatumBeforeUpdateHooks = []MicrophoneDatumHook{}

	AddMicrophoneDatumHook(boil.AfterUpdateHook, microphoneDatumAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	microphoneDatumAfterUpdateHooks = []MicrophoneDatumHook{}

	AddMicrophoneDatumHook(boil.BeforeDeleteHook, microphoneDatumBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	microphoneDatumBeforeDeleteHooks = []MicrophoneDatumHook{}

	AddMicrophoneDatumHook(boil.AfterDeleteHook, microphoneDatumAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	microphoneDatumAfterDeleteHooks = []MicrophoneDatumHook{}

	AddMicrophoneDatumHook(boil.BeforeUpsertHook, microphoneDatumBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	microphoneDatumBeforeUpsertHooks = []MicrophoneDatumHook{}

	AddMicrophoneDatumHook(boil.AfterUpsertHook, microphoneDatumAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	microphoneDatumAfterUpsertHooks = []MicrophoneDatumHook{}
}

func testMicrophoneDataInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MicrophoneDatum{}
	if err = randomize.Struct(seed, o, microphoneDatumDBTypes, true, microphoneDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MicrophoneDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := MicrophoneData().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testMicrophoneDataInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MicrophoneDatum{}
	if err = randomize.Struct(seed, o, microphoneDatumDBTypes, true); err != nil {
		t.Errorf("Unable to randomize MicrophoneDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(microphoneDatumColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := MicrophoneData().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testMicrophoneDataReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MicrophoneDatum{}
	if err = randomize.Struct(seed, o, microphoneDatumDBTypes, true, microphoneDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MicrophoneDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testMicrophoneDataReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MicrophoneDatum{}
	if err = randomize.Struct(seed, o, microphoneDatumDBTypes, true, microphoneDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MicrophoneDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := MicrophoneDatumSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testMicrophoneDataSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MicrophoneDatum{}
	if err = randomize.Struct(seed, o, microphoneDatumDBTypes, true, microphoneDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MicrophoneDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := MicrophoneData().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	microphoneDatumDBTypes = map[string]string{`ID`: `bigint`, `DeviceID`: `character varying`, `Decibels`: `numeric`, `RecordedAt`: `timestamp without time zone`}
	_                      = bytes.MinRead
)

func testMicrophoneDataUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(microphoneDatumPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(microphoneDatumAllColumns) == len(microphoneDatumPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &MicrophoneDatum{}
	if err = randomize.Struct(seed, o, microphoneDatumDBTypes, true, microphoneDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MicrophoneDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := MicrophoneData().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, microphoneDatumDBTypes, true, microphoneDatumPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize MicrophoneDatum struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testMicrophoneDataSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(microphoneDatumAllColumns) == len(microphoneDatumPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &MicrophoneDatum{}
	if err = randomize.Struct(seed, o, microphoneDatumDBTypes, true, microphoneDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MicrophoneDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := MicrophoneData().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, microphoneDatumDBTypes, true, microphoneDatumPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize MicrophoneDatum struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(microphoneDatumAllColumns, microphoneDatumPrimaryKeyColumns) {
		fields = microphoneDatumAllColumns
	} else {
		fields = strmangle.SetComplement(
			microphoneDatumAllColumns,
			microphoneDatumPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := MicrophoneDatumSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testMicrophoneDataUpsert(t *testing.T) {
	t.Parallel()

	if len(microphoneDatumAllColumns) == len(microphoneDatumPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := MicrophoneDatum{}
	if err = randomize.Struct(seed, &o, microphoneDatumDBTypes, true); err != nil {
		t.Errorf("Unable to randomize MicrophoneDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert MicrophoneDatum: %s", err)
	}

	count, err := MicrophoneData().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, microphoneDatumDBTypes, false, microphoneDatumPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize MicrophoneDatum struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert MicrophoneDatum: %s", err)
	}

	count, err = MicrophoneData().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
