// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testMotionData(t *testing.T) {
	t.Parallel()

	query := MotionData()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testMotionDataDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MotionDatum{}
	if err = randomize.Struct(seed, o, motionDatumDBTypes, true, motionDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MotionDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := MotionData().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testMotionDataQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MotionDatum{}
	if err = randomize.Struct(seed, o, motionDatumDBTypes, true, motionDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MotionDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := MotionData().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := MotionData().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testMotionDataSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MotionDatum{}
	if err = randomize.Struct(seed, o, motionDatumDBTypes, true, motionDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MotionDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := MotionDatumSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := MotionData().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testMotionDataExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MotionDatum{}
	if err = randomize.Struct(seed, o, motionDatumDBTypes, true, motionDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MotionDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := MotionDatumExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if MotionDatum exists: %s", err)
	}
	if !e {
		t.Errorf("Expected MotionDatumExists to return true, but got false.")
	}
}

func testMotionDataFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MotionDatum{}
	if err = randomize.Struct(seed, o, motionDatumDBTypes, true, motionDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MotionDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	motionDatumFound, err := FindMotionDatum(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if motionDatumFound == nil {
		t.Error("want a record, got nil")
	}
}

func testMotionDataBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MotionDatum{}
	if err = randomize.Struct(seed, o, motionDatumDBTypes, true, motionDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MotionDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = MotionData().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testMotionDataOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MotionDatum{}
	if err = randomize.Struct(seed, o, motionDatumDBTypes, true, motionDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MotionDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := MotionData().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testMotionDataAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	motionDatumOne := &MotionDatum{}
	motionDatumTwo := &MotionDatum{}
	if err = randomize.Struct(seed, motionDatumOne, motionDatumDBTypes, false, motionDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MotionDatum struct: %s", err)
	}
	if err = randomize.Struct(seed, motionDatumTwo, motionDatumDBTypes, false, motionDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MotionDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = motionDatumOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = motionDatumTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := MotionData().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testMotionDataCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	motionDatumOne := &MotionDatum{}
	motionDatumTwo := &MotionDatum{}
	if err = randomize.Struct(seed, motionDatumOne, motionDatumDBTypes, false, motionDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MotionDatum struct: %s", err)
	}
	if err = randomize.Struct(seed, motionDatumTwo, motionDatumDBTypes, false, motionDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MotionDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = motionDatumOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = motionDatumTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := MotionData().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func motionDatumBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *MotionDatum) error {
	*o = MotionDatum{}
	return nil
}

func motionDatumAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *MotionDatum) error {
	*o = MotionDatum{}
	return nil
}

func motionDatumAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *MotionDatum) error {
	*o = MotionDatum{}
	return nil
}

func motionDatumBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *MotionDatum) error {
	*o = MotionDatum{}
	return nil
}

func motionDatumAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *MotionDatum) error {
	*o = MotionDatum{}
	return nil
}

func motionDatumBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *MotionDatum) error {
	*o = MotionDatum{}
	return nil
}

func motionDatumAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *MotionDatum) error {
	*o = MotionDatum{}
	return nil
}

func motionDatumBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *MotionDatum) error {
	*o = MotionDatum{}
	return nil
}

func motionDatumAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *MotionDatum) error {
	*o = MotionDatum{}
	return nil
}

func testMotionDataHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &MotionDatum{}
	o := &MotionDatum{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, motionDatumDBTypes, false); err != nil {
		t.Errorf("Unable to randomize MotionDatum object: %s", err)
	}

	AddMotionDatumHook(boil.BeforeInsertHook, motionDatumBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	motionDatumBeforeInsertHooks = []MotionDatumHook{}

	AddMotionDatumHook(boil.AfterInsertHook, motionDatumAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	motionDatumAfterInsertHooks = []MotionDatumHook{}

	AddMotionDatumHook(boil.AfterSelectHook, motionDatumAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	motionDatumAfterSelectHooks = []MotionDatumHook{}

	AddMotionDatumHook(boil.BeforeUpdateHook, motionDatumBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	motionDatumBeforeUpdateHooks = []MotionDatumHook{}

	AddMotionDatumHook(boil.AfterUpdateHook, motionDatumAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	motionDatumAfterUpdateHooks = []MotionDatumHook{}

	AddMotionDatumHook(boil.BeforeDeleteHook, motionDatumBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	motionDatumBeforeDeleteHooks = []MotionDatumHook{}

	AddMotionDatumHook(boil.AfterDeleteHook, motionDatumAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	motionDatumAfterDeleteHooks = []MotionDatumHook{}

	AddMotionDatumHook(boil.BeforeUpsertHook, motionDatumBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	motionDatumBeforeUpsertHooks = []MotionDatumHook{}

	AddMotionDatumHook(boil.AfterUpsertHook, motionDatumAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	motionDatumAfterUpsertHooks = []MotionDatumHook{}
}

func testMotionDataInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MotionDatum{}
	if err = randomize.Struct(seed, o, motionDatumDBTypes, true, motionDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MotionDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := MotionData().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testMotionDataInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MotionDatum{}
	if err = randomize.Struct(seed, o, motionDatumDBTypes, true); err != nil {
		t.Errorf("Unable to randomize MotionDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(motionDatumColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := MotionData().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testMotionDatumToManyDatumMotionAlerts(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a MotionDatum
	var b, c MotionAlert

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, motionDatumDBTypes, true, motionDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MotionDatum struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, motionAlertDBTypes, false, motionAlertColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, motionAlertDBTypes, false, motionAlertColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&b.DataID, a.ID)
	queries.Assign(&c.DataID, a.ID)
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.DatumMotionAlerts().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if queries.Equal(v.DataID, b.DataID) {
			bFound = true
		}
		if queries.Equal(v.DataID, c.DataID) {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := MotionDatumSlice{&a}
	if err = a.L.LoadDatumMotionAlerts(ctx, tx, false, (*[]*MotionDatum)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.DatumMotionAlerts); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.DatumMotionAlerts = nil
	if err = a.L.LoadDatumMotionAlerts(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.DatumMotionAlerts); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testMotionDatumToManyAddOpDatumMotionAlerts(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a MotionDatum
	var b, c, d, e MotionAlert

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, motionDatumDBTypes, false, strmangle.SetComplement(motionDatumPrimaryKeyColumns, motionDatumColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*MotionAlert{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, motionAlertDBTypes, false, strmangle.SetComplement(motionAlertPrimaryKeyColumns, motionAlertColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*MotionAlert{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddDatumMotionAlerts(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if !queries.Equal(a.ID, first.DataID) {
			t.Error("foreign key was wrong value", a.ID, first.DataID)
		}
		if !queries.Equal(a.ID, second.DataID) {
			t.Error("foreign key was wrong value", a.ID, second.DataID)
		}

		if first.R.Datum != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.Datum != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.DatumMotionAlerts[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.DatumMotionAlerts[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.DatumMotionAlerts().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testMotionDatumToManySetOpDatumMotionAlerts(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a MotionDatum
	var b, c, d, e MotionAlert

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, motionDatumDBTypes, false, strmangle.SetComplement(motionDatumPrimaryKeyColumns, motionDatumColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*MotionAlert{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, motionAlertDBTypes, false, strmangle.SetComplement(motionAlertPrimaryKeyColumns, motionAlertColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.SetDatumMotionAlerts(ctx, tx, false, &b, &c)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.DatumMotionAlerts().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	err = a.SetDatumMotionAlerts(ctx, tx, true, &d, &e)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.DatumMotionAlerts().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.DataID) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.DataID) {
		t.Error("want c's foreign key value to be nil")
	}
	if !queries.Equal(a.ID, d.DataID) {
		t.Error("foreign key was wrong value", a.ID, d.DataID)
	}
	if !queries.Equal(a.ID, e.DataID) {
		t.Error("foreign key was wrong value", a.ID, e.DataID)
	}

	if b.R.Datum != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.Datum != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.Datum != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}
	if e.R.Datum != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}

	if a.R.DatumMotionAlerts[0] != &d {
		t.Error("relationship struct slice not set to correct value")
	}
	if a.R.DatumMotionAlerts[1] != &e {
		t.Error("relationship struct slice not set to correct value")
	}
}

func testMotionDatumToManyRemoveOpDatumMotionAlerts(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a MotionDatum
	var b, c, d, e MotionAlert

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, motionDatumDBTypes, false, strmangle.SetComplement(motionDatumPrimaryKeyColumns, motionDatumColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*MotionAlert{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, motionAlertDBTypes, false, strmangle.SetComplement(motionAlertPrimaryKeyColumns, motionAlertColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.AddDatumMotionAlerts(ctx, tx, true, foreigners...)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.DatumMotionAlerts().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 4 {
		t.Error("count was wrong:", count)
	}

	err = a.RemoveDatumMotionAlerts(ctx, tx, foreigners[:2]...)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.DatumMotionAlerts().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.DataID) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.DataID) {
		t.Error("want c's foreign key value to be nil")
	}

	if b.R.Datum != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.Datum != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.Datum != &a {
		t.Error("relationship to a should have been preserved")
	}
	if e.R.Datum != &a {
		t.Error("relationship to a should have been preserved")
	}

	if len(a.R.DatumMotionAlerts) != 2 {
		t.Error("should have preserved two relationships")
	}

	// Removal doesn't do a stable deletion for performance so we have to flip the order
	if a.R.DatumMotionAlerts[1] != &d {
		t.Error("relationship to d should have been preserved")
	}
	if a.R.DatumMotionAlerts[0] != &e {
		t.Error("relationship to e should have been preserved")
	}
}

func testMotionDataReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MotionDatum{}
	if err = randomize.Struct(seed, o, motionDatumDBTypes, true, motionDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MotionDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testMotionDataReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MotionDatum{}
	if err = randomize.Struct(seed, o, motionDatumDBTypes, true, motionDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MotionDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := MotionDatumSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testMotionDataSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MotionDatum{}
	if err = randomize.Struct(seed, o, motionDatumDBTypes, true, motionDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MotionDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := MotionData().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	motionDatumDBTypes = map[string]string{`ID`: `bigint`, `DeviceID`: `character varying`, `MotionDetected`: `boolean`, `RecordedAt`: `timestamp without time zone`}
	_                  = bytes.MinRead
)

func testMotionDataUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(motionDatumPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(motionDatumAllColumns) == len(motionDatumPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &MotionDatum{}
	if err = randomize.Struct(seed, o, motionDatumDBTypes, true, motionDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MotionDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := MotionData().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, motionDatumDBTypes, true, motionDatumPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize MotionDatum struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testMotionDataSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(motionDatumAllColumns) == len(motionDatumPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &MotionDatum{}
	if err = randomize.Struct(seed, o, motionDatumDBTypes, true, motionDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MotionDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := MotionData().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, motionDatumDBTypes, true, motionDatumPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize MotionDatum struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(motionDatumAllColumns, motionDatumPrimaryKeyColumns) {
		fields = motionDatumAllColumns
	} else {
		fields = strmangle.SetComplement(
			motionDatumAllColumns,
			motionDatumPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := MotionDatumSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testMotionDataUpsert(t *testing.T) {
	t.Parallel()

	if len(motionDatumAllColumns) == len(motionDatumPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := MotionDatum{}
	if err = randomize.Struct(seed, &o, motionDatumDBTypes, true); err != nil {
		t.Errorf("Unable to randomize MotionDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert MotionDatum: %s", err)
	}

	count, err := MotionData().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, motionDatumDBTypes, false, motionDatumPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize MotionDatum struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert MotionDatum: %s", err)
	}

	count, err = MotionData().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
