// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// MotionDatum is an object representing the database table.
type MotionDatum struct {
	ID             int64     `boil:"id" json:"id" toml:"id" yaml:"id"`
	DeviceID       string    `boil:"device_id" json:"device_id" toml:"device_id" yaml:"device_id"`
	MotionDetected bool      `boil:"motion_detected" json:"motion_detected" toml:"motion_detected" yaml:"motion_detected"`
	RecordedAt     null.Time `boil:"recorded_at" json:"recorded_at,omitempty" toml:"recorded_at" yaml:"recorded_at,omitempty"`

	R *motionDatumR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L motionDatumL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var MotionDatumColumns = struct {
	ID             string
	DeviceID       string
	MotionDetected string
	RecordedAt     string
}{
	ID:             "id",
	DeviceID:       "device_id",
	MotionDetected: "motion_detected",
	RecordedAt:     "recorded_at",
}

var MotionDatumTableColumns = struct {
	ID             string
	DeviceID       string
	MotionDetected string
	RecordedAt     string
}{
	ID:             "motion_data.id",
	DeviceID:       "motion_data.device_id",
	MotionDetected: "motion_data.motion_detected",
	RecordedAt:     "motion_data.recorded_at",
}

// Generated where

type whereHelperbool struct{ field string }

func (w whereHelperbool) EQ(x bool) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperbool) NEQ(x bool) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperbool) LT(x bool) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperbool) LTE(x bool) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperbool) GT(x bool) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperbool) GTE(x bool) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }

var MotionDatumWhere = struct {
	ID             whereHelperint64
	DeviceID       whereHelperstring
	MotionDetected whereHelperbool
	RecordedAt     whereHelpernull_Time
}{
	ID:             whereHelperint64{field: "\"motion_data\".\"id\""},
	DeviceID:       whereHelperstring{field: "\"motion_data\".\"device_id\""},
	MotionDetected: whereHelperbool{field: "\"motion_data\".\"motion_detected\""},
	RecordedAt:     whereHelpernull_Time{field: "\"motion_data\".\"recorded_at\""},
}

// MotionDatumRels is where relationship names are stored.
var MotionDatumRels = struct {
}{}

// motionDatumR is where relationships are stored.
type motionDatumR struct {
}

// NewStruct creates a new relationship struct
func (*motionDatumR) NewStruct() *motionDatumR {
	return &motionDatumR{}
}

// motionDatumL is where Load methods for each relationship are stored.
type motionDatumL struct{}

var (
	motionDatumAllColumns            = []string{"id", "device_id", "motion_detected", "recorded_at"}
	motionDatumColumnsWithoutDefault = []string{"device_id", "motion_detected"}
	motionDatumColumnsWithDefault    = []string{"id", "recorded_at"}
	motionDatumPrimaryKeyColumns     = []string{"id"}
	motionDatumGeneratedColumns      = []string{}
)

type (
	// MotionDatumSlice is an alias for a slice of pointers to MotionDatum.
	// This should almost always be used instead of []MotionDatum.
	MotionDatumSlice []*MotionDatum
	// MotionDatumHook is the signature for custom MotionDatum hook methods
	MotionDatumHook func(context.Context, boil.ContextExecutor, *MotionDatum) error

	motionDatumQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	motionDatumType                 = reflect.TypeOf(&MotionDatum{})
	motionDatumMapping              = queries.MakeStructMapping(motionDatumType)
	motionDatumPrimaryKeyMapping, _ = queries.BindMapping(motionDatumType, motionDatumMapping, motionDatumPrimaryKeyColumns)
	motionDatumInsertCacheMut       sync.RWMutex
	motionDatumInsertCache          = make(map[string]insertCache)
	motionDatumUpdateCacheMut       sync.RWMutex
	motionDatumUpdateCache          = make(map[string]updateCache)
	motionDatumUpsertCacheMut       sync.RWMutex
	motionDatumUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var motionDatumAfterSelectMu sync.Mutex
var motionDatumAfterSelectHooks []MotionDatumHook

var motionDatumBeforeInsertMu sync.Mutex
var motionDatumBeforeInsertHooks []MotionDatumHook
var motionDatumAfterInsertMu sync.Mutex
var motionDatumAfterInsertHooks []MotionDatumHook

var motionDatumBeforeUpdateMu sync.Mutex
var motionDatumBeforeUpdateHooks []MotionDatumHook
var motionDatumAfterUpdateMu sync.Mutex
var motionDatumAfterUpdateHooks []MotionDatumHook

var motionDatumBeforeDeleteMu sync.Mutex
var motionDatumBeforeDeleteHooks []MotionDatumHook
var motionDatumAfterDeleteMu sync.Mutex
var motionDatumAfterDeleteHooks []MotionDatumHook

var motionDatumBeforeUpsertMu sync.Mutex
var motionDatumBeforeUpsertHooks []MotionDatumHook
var motionDatumAfterUpsertMu sync.Mutex
var motionDatumAfterUpsertHooks []MotionDatumHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *MotionDatum) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range motionDatumAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *MotionDatum) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range motionDatumBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *MotionDatum) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range motionDatumAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *MotionDatum) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range motionDatumBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *MotionDatum) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range motionDatumAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *MotionDatum) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range motionDatumBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *MotionDatum) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range motionDatumAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *MotionDatum) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range motionDatumBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *MotionDatum) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range motionDatumAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddMotionDatumHook registers your hook function for all future operations.
func AddMotionDatumHook(hookPoint boil.HookPoint, motionDatumHook MotionDatumHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		motionDatumAfterSelectMu.Lock()
		motionDatumAfterSelectHooks = append(motionDatumAfterSelectHooks, motionDatumHook)
		motionDatumAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		motionDatumBeforeInsertMu.Lock()
		motionDatumBeforeInsertHooks = append(motionDatumBeforeInsertHooks, motionDatumHook)
		motionDatumBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		motionDatumAfterInsertMu.Lock()
		motionDatumAfterInsertHooks = append(motionDatumAfterInsertHooks, motionDatumHook)
		motionDatumAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		motionDatumBeforeUpdateMu.Lock()
		motionDatumBeforeUpdateHooks = append(motionDatumBeforeUpdateHooks, motionDatumHook)
		motionDatumBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		motionDatumAfterUpdateMu.Lock()
		motionDatumAfterUpdateHooks = append(motionDatumAfterUpdateHooks, motionDatumHook)
		motionDatumAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		motionDatumBeforeDeleteMu.Lock()
		motionDatumBeforeDeleteHooks = append(motionDatumBeforeDeleteHooks, motionDatumHook)
		motionDatumBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		motionDatumAfterDeleteMu.Lock()
		motionDatumAfterDeleteHooks = append(motionDatumAfterDeleteHooks, motionDatumHook)
		motionDatumAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		motionDatumBeforeUpsertMu.Lock()
		motionDatumBeforeUpsertHooks = append(motionDatumBeforeUpsertHooks, motionDatumHook)
		motionDatumBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		motionDatumAfterUpsertMu.Lock()
		motionDatumAfterUpsertHooks = append(motionDatumAfterUpsertHooks, motionDatumHook)
		motionDatumAfterUpsertMu.Unlock()
	}
}

// One returns a single motionDatum record from the query.
func (q motionDatumQuery) One(ctx context.Context, exec boil.ContextExecutor) (*MotionDatum, error) {
	o := &MotionDatum{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for motion_data")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all MotionDatum records from the query.
func (q motionDatumQuery) All(ctx context.Context, exec boil.ContextExecutor) (MotionDatumSlice, error) {
	var o []*MotionDatum

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to MotionDatum slice")
	}

	if len(motionDatumAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all MotionDatum records in the query.
func (q motionDatumQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count motion_data rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q motionDatumQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if motion_data exists")
	}

	return count > 0, nil
}

// MotionData retrieves all the records using an executor.
func MotionData(mods ...qm.QueryMod) motionDatumQuery {
	mods = append(mods, qm.From("\"motion_data\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"motion_data\".*"})
	}

	return motionDatumQuery{q}
}

// FindMotionDatum retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindMotionDatum(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*MotionDatum, error) {
	motionDatumObj := &MotionDatum{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"motion_data\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, motionDatumObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from motion_data")
	}

	if err = motionDatumObj.doAfterSelectHooks(ctx, exec); err != nil {
		return motionDatumObj, err
	}

	return motionDatumObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *MotionDatum) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no motion_data provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(motionDatumColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	motionDatumInsertCacheMut.RLock()
	cache, cached := motionDatumInsertCache[key]
	motionDatumInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			motionDatumAllColumns,
			motionDatumColumnsWithDefault,
			motionDatumColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(motionDatumType, motionDatumMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(motionDatumType, motionDatumMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"motion_data\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"motion_data\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into motion_data")
	}

	if !cached {
		motionDatumInsertCacheMut.Lock()
		motionDatumInsertCache[key] = cache
		motionDatumInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the MotionDatum.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *MotionDatum) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	motionDatumUpdateCacheMut.RLock()
	cache, cached := motionDatumUpdateCache[key]
	motionDatumUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			motionDatumAllColumns,
			motionDatumPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update motion_data, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"motion_data\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, motionDatumPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(motionDatumType, motionDatumMapping, append(wl, motionDatumPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update motion_data row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for motion_data")
	}

	if !cached {
		motionDatumUpdateCacheMut.Lock()
		motionDatumUpdateCache[key] = cache
		motionDatumUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q motionDatumQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for motion_data")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for motion_data")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o MotionDatumSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), motionDatumPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"motion_data\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, motionDatumPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in motionDatum slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all motionDatum")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *MotionDatum) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no motion_data provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(motionDatumColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	motionDatumUpsertCacheMut.RLock()
	cache, cached := motionDatumUpsertCache[key]
	motionDatumUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			motionDatumAllColumns,
			motionDatumColumnsWithDefault,
			motionDatumColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			motionDatumAllColumns,
			motionDatumPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert motion_data, could not build update column list")
		}

		ret := strmangle.SetComplement(motionDatumAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(motionDatumPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert motion_data, could not build conflict column list")
			}

			conflict = make([]string, len(motionDatumPrimaryKeyColumns))
			copy(conflict, motionDatumPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"motion_data\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(motionDatumType, motionDatumMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(motionDatumType, motionDatumMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert motion_data")
	}

	if !cached {
		motionDatumUpsertCacheMut.Lock()
		motionDatumUpsertCache[key] = cache
		motionDatumUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single MotionDatum record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *MotionDatum) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no MotionDatum provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), motionDatumPrimaryKeyMapping)
	sql := "DELETE FROM \"motion_data\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from motion_data")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for motion_data")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q motionDatumQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no motionDatumQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from motion_data")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for motion_data")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o MotionDatumSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(motionDatumBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), motionDatumPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"motion_data\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, motionDatumPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from motionDatum slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for motion_data")
	}

	if len(motionDatumAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *MotionDatum) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindMotionDatum(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *MotionDatumSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := MotionDatumSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), motionDatumPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"motion_data\".* FROM \"motion_data\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, motionDatumPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in MotionDatumSlice")
	}

	*o = slice

	return nil
}

// MotionDatumExists checks if the MotionDatum row exists.
func MotionDatumExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"motion_data\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if motion_data exists")
	}

	return exists, nil
}

// Exists checks if the MotionDatum row exists.
func (o *MotionDatum) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return MotionDatumExists(ctx, exec, o.ID)
}
