// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testMotionAlerts(t *testing.T) {
	t.Parallel()

	query := MotionAlerts()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testMotionAlertsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MotionAlert{}
	if err = randomize.Struct(seed, o, motionAlertDBTypes, true, motionAlertColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MotionAlert struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := MotionAlerts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testMotionAlertsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MotionAlert{}
	if err = randomize.Struct(seed, o, motionAlertDBTypes, true, motionAlertColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MotionAlert struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := MotionAlerts().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := MotionAlerts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testMotionAlertsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MotionAlert{}
	if err = randomize.Struct(seed, o, motionAlertDBTypes, true, motionAlertColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MotionAlert struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := MotionAlertSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := MotionAlerts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testMotionAlertsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MotionAlert{}
	if err = randomize.Struct(seed, o, motionAlertDBTypes, true, motionAlertColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MotionAlert struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := MotionAlertExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if MotionAlert exists: %s", err)
	}
	if !e {
		t.Errorf("Expected MotionAlertExists to return true, but got false.")
	}
}

func testMotionAlertsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MotionAlert{}
	if err = randomize.Struct(seed, o, motionAlertDBTypes, true, motionAlertColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MotionAlert struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	motionAlertFound, err := FindMotionAlert(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if motionAlertFound == nil {
		t.Error("want a record, got nil")
	}
}

func testMotionAlertsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MotionAlert{}
	if err = randomize.Struct(seed, o, motionAlertDBTypes, true, motionAlertColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MotionAlert struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = MotionAlerts().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testMotionAlertsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MotionAlert{}
	if err = randomize.Struct(seed, o, motionAlertDBTypes, true, motionAlertColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MotionAlert struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := MotionAlerts().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testMotionAlertsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	motionAlertOne := &MotionAlert{}
	motionAlertTwo := &MotionAlert{}
	if err = randomize.Struct(seed, motionAlertOne, motionAlertDBTypes, false, motionAlertColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MotionAlert struct: %s", err)
	}
	if err = randomize.Struct(seed, motionAlertTwo, motionAlertDBTypes, false, motionAlertColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MotionAlert struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = motionAlertOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = motionAlertTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := MotionAlerts().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testMotionAlertsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	motionAlertOne := &MotionAlert{}
	motionAlertTwo := &MotionAlert{}
	if err = randomize.Struct(seed, motionAlertOne, motionAlertDBTypes, false, motionAlertColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MotionAlert struct: %s", err)
	}
	if err = randomize.Struct(seed, motionAlertTwo, motionAlertDBTypes, false, motionAlertColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MotionAlert struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = motionAlertOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = motionAlertTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := MotionAlerts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func motionAlertBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *MotionAlert) error {
	*o = MotionAlert{}
	return nil
}

func motionAlertAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *MotionAlert) error {
	*o = MotionAlert{}
	return nil
}

func motionAlertAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *MotionAlert) error {
	*o = MotionAlert{}
	return nil
}

func motionAlertBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *MotionAlert) error {
	*o = MotionAlert{}
	return nil
}

func motionAlertAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *MotionAlert) error {
	*o = MotionAlert{}
	return nil
}

func motionAlertBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *MotionAlert) error {
	*o = MotionAlert{}
	return nil
}

func motionAlertAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *MotionAlert) error {
	*o = MotionAlert{}
	return nil
}

func motionAlertBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *MotionAlert) error {
	*o = MotionAlert{}
	return nil
}

func motionAlertAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *MotionAlert) error {
	*o = MotionAlert{}
	return nil
}

func testMotionAlertsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &MotionAlert{}
	o := &MotionAlert{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, motionAlertDBTypes, false); err != nil {
		t.Errorf("Unable to randomize MotionAlert object: %s", err)
	}

	AddMotionAlertHook(boil.BeforeInsertHook, motionAlertBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	motionAlertBeforeInsertHooks = []MotionAlertHook{}

	AddMotionAlertHook(boil.AfterInsertHook, motionAlertAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	motionAlertAfterInsertHooks = []MotionAlertHook{}

	AddMotionAlertHook(boil.AfterSelectHook, motionAlertAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	motionAlertAfterSelectHooks = []MotionAlertHook{}

	AddMotionAlertHook(boil.BeforeUpdateHook, motionAlertBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	motionAlertBeforeUpdateHooks = []MotionAlertHook{}

	AddMotionAlertHook(boil.AfterUpdateHook, motionAlertAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	motionAlertAfterUpdateHooks = []MotionAlertHook{}

	AddMotionAlertHook(boil.BeforeDeleteHook, motionAlertBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	motionAlertBeforeDeleteHooks = []MotionAlertHook{}

	AddMotionAlertHook(boil.AfterDeleteHook, motionAlertAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	motionAlertAfterDeleteHooks = []MotionAlertHook{}

	AddMotionAlertHook(boil.BeforeUpsertHook, motionAlertBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	motionAlertBeforeUpsertHooks = []MotionAlertHook{}

	AddMotionAlertHook(boil.AfterUpsertHook, motionAlertAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	motionAlertAfterUpsertHooks = []MotionAlertHook{}
}

func testMotionAlertsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MotionAlert{}
	if err = randomize.Struct(seed, o, motionAlertDBTypes, true, motionAlertColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MotionAlert struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := MotionAlerts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testMotionAlertsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MotionAlert{}
	if err = randomize.Struct(seed, o, motionAlertDBTypes, true); err != nil {
		t.Errorf("Unable to randomize MotionAlert struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(motionAlertColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := MotionAlerts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testMotionAlertToOneMotionDatumUsingDatum(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local MotionAlert
	var foreign MotionDatum

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, motionAlertDBTypes, true, motionAlertColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MotionAlert struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, motionDatumDBTypes, false, motionDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MotionDatum struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&local.DataID, foreign.ID)
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Datum().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if !queries.Equal(check.ID, foreign.ID) {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	ranAfterSelectHook := false
	AddMotionDatumHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *MotionDatum) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := MotionAlertSlice{&local}
	if err = local.L.LoadDatum(ctx, tx, false, (*[]*MotionAlert)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Datum == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Datum = nil
	if err = local.L.LoadDatum(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Datum == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testMotionAlertToOneSetOpMotionDatumUsingDatum(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a MotionAlert
	var b, c MotionDatum

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, motionAlertDBTypes, false, strmangle.SetComplement(motionAlertPrimaryKeyColumns, motionAlertColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, motionDatumDBTypes, false, strmangle.SetComplement(motionDatumPrimaryKeyColumns, motionDatumColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, motionDatumDBTypes, false, strmangle.SetComplement(motionDatumPrimaryKeyColumns, motionDatumColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*MotionDatum{&b, &c} {
		err = a.SetDatum(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Datum != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.DatumMotionAlerts[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if !queries.Equal(a.DataID, x.ID) {
			t.Error("foreign key was wrong value", a.DataID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.DataID))
		reflect.Indirect(reflect.ValueOf(&a.DataID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if !queries.Equal(a.DataID, x.ID) {
			t.Error("foreign key was wrong value", a.DataID, x.ID)
		}
	}
}

func testMotionAlertToOneRemoveOpMotionDatumUsingDatum(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a MotionAlert
	var b MotionDatum

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, motionAlertDBTypes, false, strmangle.SetComplement(motionAlertPrimaryKeyColumns, motionAlertColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, motionDatumDBTypes, false, strmangle.SetComplement(motionDatumPrimaryKeyColumns, motionDatumColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = a.SetDatum(ctx, tx, true, &b); err != nil {
		t.Fatal(err)
	}

	if err = a.RemoveDatum(ctx, tx, &b); err != nil {
		t.Error("failed to remove relationship")
	}

	count, err := a.Datum().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 0 {
		t.Error("want no relationships remaining")
	}

	if a.R.Datum != nil {
		t.Error("R struct entry should be nil")
	}

	if !queries.IsValuerNil(a.DataID) {
		t.Error("foreign key value should be nil")
	}

	if len(b.R.DatumMotionAlerts) != 0 {
		t.Error("failed to remove a from b's relationships")
	}
}

func testMotionAlertsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MotionAlert{}
	if err = randomize.Struct(seed, o, motionAlertDBTypes, true, motionAlertColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MotionAlert struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testMotionAlertsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MotionAlert{}
	if err = randomize.Struct(seed, o, motionAlertDBTypes, true, motionAlertColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MotionAlert struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := MotionAlertSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testMotionAlertsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MotionAlert{}
	if err = randomize.Struct(seed, o, motionAlertDBTypes, true, motionAlertColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MotionAlert struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := MotionAlerts().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	motionAlertDBTypes = map[string]string{`ID`: `bigint`, `DeviceID`: `character varying`, `DataID`: `bigint`, `MotionDetected`: `boolean`, `AlertReason`: `character varying`, `AlertStatus`: `character varying`, `AcknowledgedAt`: `timestamp without time zone`, `ResolvedAt`: `timestamp without time zone`, `CreatedAt`: `timestamp without time zone`}
	_                  = bytes.MinRead
)

func testMotionAlertsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(motionAlertPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(motionAlertAllColumns) == len(motionAlertPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &MotionAlert{}
	if err = randomize.Struct(seed, o, motionAlertDBTypes, true, motionAlertColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MotionAlert struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := MotionAlerts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, motionAlertDBTypes, true, motionAlertPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize MotionAlert struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testMotionAlertsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(motionAlertAllColumns) == len(motionAlertPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &MotionAlert{}
	if err = randomize.Struct(seed, o, motionAlertDBTypes, true, motionAlertColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MotionAlert struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := MotionAlerts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, motionAlertDBTypes, true, motionAlertPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize MotionAlert struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(motionAlertAllColumns, motionAlertPrimaryKeyColumns) {
		fields = motionAlertAllColumns
	} else {
		fields = strmangle.SetComplement(
			motionAlertAllColumns,
			motionAlertPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := MotionAlertSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testMotionAlertsUpsert(t *testing.T) {
	t.Parallel()

	if len(motionAlertAllColumns) == len(motionAlertPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := MotionAlert{}
	if err = randomize.Struct(seed, &o, motionAlertDBTypes, true); err != nil {
		t.Errorf("Unable to randomize MotionAlert struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert MotionAlert: %s", err)
	}

	count, err := MotionAlerts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, motionAlertDBTypes, false, motionAlertPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize MotionAlert struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert MotionAlert: %s", err)
	}

	count, err = MotionAlerts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
