// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

// This test suite runs each operation test in parallel.
// Example, if your database has 3 tables, the suite will run:
// table1, table2 and table3 Delete in parallel
// table1, table2 and table3 Insert in parallel, and so forth.
// It does NOT run each operation group in parallel.
// Separating the tests thusly grants avoidance of Postgres deadlocks.
func TestParent(t *testing.T) {
	t.Run("DistanceData", testDistanceData)
	t.Run("MicrophoneData", testMicrophoneData)
	t.Run("MotionData", testMotionData)
	t.Run("PushTokens", testPushTokens)
}

func TestDelete(t *testing.T) {
	t.Run("DistanceData", testDistanceDataDelete)
	t.Run("MicrophoneData", testMicrophoneDataDelete)
	t.Run("MotionData", testMotionDataDelete)
	t.Run("PushTokens", testPushTokensDelete)
}

func TestQueryDeleteAll(t *testing.T) {
	t.Run("DistanceData", testDistanceDataQueryDeleteAll)
	t.Run("MicrophoneData", testMicrophoneDataQueryDeleteAll)
	t.Run("MotionData", testMotionDataQueryDeleteAll)
	t.Run("PushTokens", testPushTokensQueryDeleteAll)
}

func TestSliceDeleteAll(t *testing.T) {
	t.Run("DistanceData", testDistanceDataSliceDeleteAll)
	t.Run("MicrophoneData", testMicrophoneDataSliceDeleteAll)
	t.Run("MotionData", testMotionDataSliceDeleteAll)
	t.Run("PushTokens", testPushTokensSliceDeleteAll)
}

func TestExists(t *testing.T) {
	t.Run("DistanceData", testDistanceDataExists)
	t.Run("MicrophoneData", testMicrophoneDataExists)
	t.Run("MotionData", testMotionDataExists)
	t.Run("PushTokens", testPushTokensExists)
}

func TestFind(t *testing.T) {
	t.Run("DistanceData", testDistanceDataFind)
	t.Run("MicrophoneData", testMicrophoneDataFind)
	t.Run("MotionData", testMotionDataFind)
	t.Run("PushTokens", testPushTokensFind)
}

func TestBind(t *testing.T) {
	t.Run("DistanceData", testDistanceDataBind)
	t.Run("MicrophoneData", testMicrophoneDataBind)
	t.Run("MotionData", testMotionDataBind)
	t.Run("PushTokens", testPushTokensBind)
}

func TestOne(t *testing.T) {
	t.Run("DistanceData", testDistanceDataOne)
	t.Run("MicrophoneData", testMicrophoneDataOne)
	t.Run("MotionData", testMotionDataOne)
	t.Run("PushTokens", testPushTokensOne)
}

func TestAll(t *testing.T) {
	t.Run("DistanceData", testDistanceDataAll)
	t.Run("MicrophoneData", testMicrophoneDataAll)
	t.Run("MotionData", testMotionDataAll)
	t.Run("PushTokens", testPushTokensAll)
}

func TestCount(t *testing.T) {
	t.Run("DistanceData", testDistanceDataCount)
	t.Run("MicrophoneData", testMicrophoneDataCount)
	t.Run("MotionData", testMotionDataCount)
	t.Run("PushTokens", testPushTokensCount)
}

func TestHooks(t *testing.T) {
	t.Run("DistanceData", testDistanceDataHooks)
	t.Run("MicrophoneData", testMicrophoneDataHooks)
	t.Run("MotionData", testMotionDataHooks)
	t.Run("PushTokens", testPushTokensHooks)
}

func TestInsert(t *testing.T) {
	t.Run("DistanceData", testDistanceDataInsert)
	t.Run("DistanceData", testDistanceDataInsertWhitelist)
	t.Run("MicrophoneData", testMicrophoneDataInsert)
	t.Run("MicrophoneData", testMicrophoneDataInsertWhitelist)
	t.Run("MotionData", testMotionDataInsert)
	t.Run("MotionData", testMotionDataInsertWhitelist)
	t.Run("PushTokens", testPushTokensInsert)
	t.Run("PushTokens", testPushTokensInsertWhitelist)
}

func TestReload(t *testing.T) {
	t.Run("DistanceData", testDistanceDataReload)
	t.Run("MicrophoneData", testMicrophoneDataReload)
	t.Run("MotionData", testMotionDataReload)
	t.Run("PushTokens", testPushTokensReload)
}

func TestReloadAll(t *testing.T) {
	t.Run("DistanceData", testDistanceDataReloadAll)
	t.Run("MicrophoneData", testMicrophoneDataReloadAll)
	t.Run("MotionData", testMotionDataReloadAll)
	t.Run("PushTokens", testPushTokensReloadAll)
}

func TestSelect(t *testing.T) {
	t.Run("DistanceData", testDistanceDataSelect)
	t.Run("MicrophoneData", testMicrophoneDataSelect)
	t.Run("MotionData", testMotionDataSelect)
	t.Run("PushTokens", testPushTokensSelect)
}

func TestUpdate(t *testing.T) {
	t.Run("DistanceData", testDistanceDataUpdate)
	t.Run("MicrophoneData", testMicrophoneDataUpdate)
	t.Run("MotionData", testMotionDataUpdate)
	t.Run("PushTokens", testPushTokensUpdate)
}

func TestSliceUpdateAll(t *testing.T) {
	t.Run("DistanceData", testDistanceDataSliceUpdateAll)
	t.Run("MicrophoneData", testMicrophoneDataSliceUpdateAll)
	t.Run("MotionData", testMotionDataSliceUpdateAll)
	t.Run("PushTokens", testPushTokensSliceUpdateAll)
}
