// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	DistanceAlerts   string
	DistanceData     string
	MicrophoneAlerts string
	MicrophoneData   string
	MotionAlerts     string
	MotionData       string
	PushTokens       string
}{
	DistanceAlerts:   "distance_alerts",
	DistanceData:     "distance_data",
	MicrophoneAlerts: "microphone_alerts",
	MicrophoneData:   "microphone_data",
	MotionAlerts:     "motion_alerts",
	MotionData:       "motion_data",
	PushTokens:       "push_tokens",
}
