// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testDistanceData(t *testing.T) {
	t.Parallel()

	query := DistanceData()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testDistanceDataDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DistanceDatum{}
	if err = randomize.Struct(seed, o, distanceDatumDBTypes, true, distanceDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DistanceDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := DistanceData().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testDistanceDataQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DistanceDatum{}
	if err = randomize.Struct(seed, o, distanceDatumDBTypes, true, distanceDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DistanceDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := DistanceData().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := DistanceData().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testDistanceDataSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DistanceDatum{}
	if err = randomize.Struct(seed, o, distanceDatumDBTypes, true, distanceDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DistanceDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := DistanceDatumSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := DistanceData().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testDistanceDataExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DistanceDatum{}
	if err = randomize.Struct(seed, o, distanceDatumDBTypes, true, distanceDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DistanceDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := DistanceDatumExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if DistanceDatum exists: %s", err)
	}
	if !e {
		t.Errorf("Expected DistanceDatumExists to return true, but got false.")
	}
}

func testDistanceDataFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DistanceDatum{}
	if err = randomize.Struct(seed, o, distanceDatumDBTypes, true, distanceDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DistanceDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	distanceDatumFound, err := FindDistanceDatum(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if distanceDatumFound == nil {
		t.Error("want a record, got nil")
	}
}

func testDistanceDataBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DistanceDatum{}
	if err = randomize.Struct(seed, o, distanceDatumDBTypes, true, distanceDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DistanceDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = DistanceData().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testDistanceDataOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DistanceDatum{}
	if err = randomize.Struct(seed, o, distanceDatumDBTypes, true, distanceDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DistanceDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := DistanceData().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testDistanceDataAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	distanceDatumOne := &DistanceDatum{}
	distanceDatumTwo := &DistanceDatum{}
	if err = randomize.Struct(seed, distanceDatumOne, distanceDatumDBTypes, false, distanceDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DistanceDatum struct: %s", err)
	}
	if err = randomize.Struct(seed, distanceDatumTwo, distanceDatumDBTypes, false, distanceDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DistanceDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = distanceDatumOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = distanceDatumTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := DistanceData().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testDistanceDataCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	distanceDatumOne := &DistanceDatum{}
	distanceDatumTwo := &DistanceDatum{}
	if err = randomize.Struct(seed, distanceDatumOne, distanceDatumDBTypes, false, distanceDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DistanceDatum struct: %s", err)
	}
	if err = randomize.Struct(seed, distanceDatumTwo, distanceDatumDBTypes, false, distanceDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DistanceDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = distanceDatumOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = distanceDatumTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := DistanceData().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func distanceDatumBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *DistanceDatum) error {
	*o = DistanceDatum{}
	return nil
}

func distanceDatumAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *DistanceDatum) error {
	*o = DistanceDatum{}
	return nil
}

func distanceDatumAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *DistanceDatum) error {
	*o = DistanceDatum{}
	return nil
}

func distanceDatumBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *DistanceDatum) error {
	*o = DistanceDatum{}
	return nil
}

func distanceDatumAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *DistanceDatum) error {
	*o = DistanceDatum{}
	return nil
}

func distanceDatumBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *DistanceDatum) error {
	*o = DistanceDatum{}
	return nil
}

func distanceDatumAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *DistanceDatum) error {
	*o = DistanceDatum{}
	return nil
}

func distanceDatumBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *DistanceDatum) error {
	*o = DistanceDatum{}
	return nil
}

func distanceDatumAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *DistanceDatum) error {
	*o = DistanceDatum{}
	return nil
}

func testDistanceDataHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &DistanceDatum{}
	o := &DistanceDatum{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, distanceDatumDBTypes, false); err != nil {
		t.Errorf("Unable to randomize DistanceDatum object: %s", err)
	}

	AddDistanceDatumHook(boil.BeforeInsertHook, distanceDatumBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	distanceDatumBeforeInsertHooks = []DistanceDatumHook{}

	AddDistanceDatumHook(boil.AfterInsertHook, distanceDatumAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	distanceDatumAfterInsertHooks = []DistanceDatumHook{}

	AddDistanceDatumHook(boil.AfterSelectHook, distanceDatumAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	distanceDatumAfterSelectHooks = []DistanceDatumHook{}

	AddDistanceDatumHook(boil.BeforeUpdateHook, distanceDatumBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	distanceDatumBeforeUpdateHooks = []DistanceDatumHook{}

	AddDistanceDatumHook(boil.AfterUpdateHook, distanceDatumAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	distanceDatumAfterUpdateHooks = []DistanceDatumHook{}

	AddDistanceDatumHook(boil.BeforeDeleteHook, distanceDatumBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	distanceDatumBeforeDeleteHooks = []DistanceDatumHook{}

	AddDistanceDatumHook(boil.AfterDeleteHook, distanceDatumAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	distanceDatumAfterDeleteHooks = []DistanceDatumHook{}

	AddDistanceDatumHook(boil.BeforeUpsertHook, distanceDatumBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	distanceDatumBeforeUpsertHooks = []DistanceDatumHook{}

	AddDistanceDatumHook(boil.AfterUpsertHook, distanceDatumAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	distanceDatumAfterUpsertHooks = []DistanceDatumHook{}
}

func testDistanceDataInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DistanceDatum{}
	if err = randomize.Struct(seed, o, distanceDatumDBTypes, true, distanceDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DistanceDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := DistanceData().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testDistanceDataInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DistanceDatum{}
	if err = randomize.Struct(seed, o, distanceDatumDBTypes, true); err != nil {
		t.Errorf("Unable to randomize DistanceDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(distanceDatumColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := DistanceData().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testDistanceDataReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DistanceDatum{}
	if err = randomize.Struct(seed, o, distanceDatumDBTypes, true, distanceDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DistanceDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testDistanceDataReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DistanceDatum{}
	if err = randomize.Struct(seed, o, distanceDatumDBTypes, true, distanceDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DistanceDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := DistanceDatumSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testDistanceDataSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DistanceDatum{}
	if err = randomize.Struct(seed, o, distanceDatumDBTypes, true, distanceDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DistanceDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := DistanceData().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	distanceDatumDBTypes = map[string]string{`ID`: `bigint`, `DeviceID`: `character varying`, `DistanceCM`: `numeric`, `RecordedAt`: `timestamp without time zone`}
	_                    = bytes.MinRead
)

func testDistanceDataUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(distanceDatumPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(distanceDatumAllColumns) == len(distanceDatumPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &DistanceDatum{}
	if err = randomize.Struct(seed, o, distanceDatumDBTypes, true, distanceDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DistanceDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := DistanceData().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, distanceDatumDBTypes, true, distanceDatumPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize DistanceDatum struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testDistanceDataSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(distanceDatumAllColumns) == len(distanceDatumPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &DistanceDatum{}
	if err = randomize.Struct(seed, o, distanceDatumDBTypes, true, distanceDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DistanceDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := DistanceData().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, distanceDatumDBTypes, true, distanceDatumPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize DistanceDatum struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(distanceDatumAllColumns, distanceDatumPrimaryKeyColumns) {
		fields = distanceDatumAllColumns
	} else {
		fields = strmangle.SetComplement(
			distanceDatumAllColumns,
			distanceDatumPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := DistanceDatumSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testDistanceDataUpsert(t *testing.T) {
	t.Parallel()

	if len(distanceDatumAllColumns) == len(distanceDatumPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := DistanceDatum{}
	if err = randomize.Struct(seed, &o, distanceDatumDBTypes, true); err != nil {
		t.Errorf("Unable to randomize DistanceDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert DistanceDatum: %s", err)
	}

	count, err := DistanceData().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, distanceDatumDBTypes, false, distanceDatumPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize DistanceDatum struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert DistanceDatum: %s", err)
	}

	count, err = DistanceData().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
