// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/sqlboiler/v4/types"
	"github.com/volatiletech/strmangle"
)

// DistanceDatum is an object representing the database table.
type DistanceDatum struct {
	ID         int64         `boil:"id" json:"id" toml:"id" yaml:"id"`
	DeviceID   string        `boil:"device_id" json:"device_id" toml:"device_id" yaml:"device_id"`
	DistanceCM types.Decimal `boil:"distance_cm" json:"distance_cm" toml:"distance_cm" yaml:"distance_cm"`
	RecordedAt null.Time     `boil:"recorded_at" json:"recorded_at,omitempty" toml:"recorded_at" yaml:"recorded_at,omitempty"`

	R *distanceDatumR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L distanceDatumL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var DistanceDatumColumns = struct {
	ID         string
	DeviceID   string
	DistanceCM string
	RecordedAt string
}{
	ID:         "id",
	DeviceID:   "device_id",
	DistanceCM: "distance_cm",
	RecordedAt: "recorded_at",
}

var DistanceDatumTableColumns = struct {
	ID         string
	DeviceID   string
	DistanceCM string
	RecordedAt string
}{
	ID:         "distance_data.id",
	DeviceID:   "distance_data.device_id",
	DistanceCM: "distance_data.distance_cm",
	RecordedAt: "distance_data.recorded_at",
}

// Generated where

var DistanceDatumWhere = struct {
	ID         whereHelperint64
	DeviceID   whereHelperstring
	DistanceCM whereHelpertypes_Decimal
	RecordedAt whereHelpernull_Time
}{
	ID:         whereHelperint64{field: "\"distance_data\".\"id\""},
	DeviceID:   whereHelperstring{field: "\"distance_data\".\"device_id\""},
	DistanceCM: whereHelpertypes_Decimal{field: "\"distance_data\".\"distance_cm\""},
	RecordedAt: whereHelpernull_Time{field: "\"distance_data\".\"recorded_at\""},
}

// DistanceDatumRels is where relationship names are stored.
var DistanceDatumRels = struct {
	DatumDistanceAlerts string
}{
	DatumDistanceAlerts: "DatumDistanceAlerts",
}

// distanceDatumR is where relationships are stored.
type distanceDatumR struct {
	DatumDistanceAlerts DistanceAlertSlice `boil:"DatumDistanceAlerts" json:"DatumDistanceAlerts" toml:"DatumDistanceAlerts" yaml:"DatumDistanceAlerts"`
}

// NewStruct creates a new relationship struct
func (*distanceDatumR) NewStruct() *distanceDatumR {
	return &distanceDatumR{}
}

func (r *distanceDatumR) GetDatumDistanceAlerts() DistanceAlertSlice {
	if r == nil {
		return nil
	}
	return r.DatumDistanceAlerts
}

// distanceDatumL is where Load methods for each relationship are stored.
type distanceDatumL struct{}

var (
	distanceDatumAllColumns            = []string{"id", "device_id", "distance_cm", "recorded_at"}
	distanceDatumColumnsWithoutDefault = []string{"device_id", "distance_cm"}
	distanceDatumColumnsWithDefault    = []string{"id", "recorded_at"}
	distanceDatumPrimaryKeyColumns     = []string{"id"}
	distanceDatumGeneratedColumns      = []string{}
)

type (
	// DistanceDatumSlice is an alias for a slice of pointers to DistanceDatum.
	// This should almost always be used instead of []DistanceDatum.
	DistanceDatumSlice []*DistanceDatum
	// DistanceDatumHook is the signature for custom DistanceDatum hook methods
	DistanceDatumHook func(context.Context, boil.ContextExecutor, *DistanceDatum) error

	distanceDatumQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	distanceDatumType                 = reflect.TypeOf(&DistanceDatum{})
	distanceDatumMapping              = queries.MakeStructMapping(distanceDatumType)
	distanceDatumPrimaryKeyMapping, _ = queries.BindMapping(distanceDatumType, distanceDatumMapping, distanceDatumPrimaryKeyColumns)
	distanceDatumInsertCacheMut       sync.RWMutex
	distanceDatumInsertCache          = make(map[string]insertCache)
	distanceDatumUpdateCacheMut       sync.RWMutex
	distanceDatumUpdateCache          = make(map[string]updateCache)
	distanceDatumUpsertCacheMut       sync.RWMutex
	distanceDatumUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var distanceDatumAfterSelectMu sync.Mutex
var distanceDatumAfterSelectHooks []DistanceDatumHook

var distanceDatumBeforeInsertMu sync.Mutex
var distanceDatumBeforeInsertHooks []DistanceDatumHook
var distanceDatumAfterInsertMu sync.Mutex
var distanceDatumAfterInsertHooks []DistanceDatumHook

var distanceDatumBeforeUpdateMu sync.Mutex
var distanceDatumBeforeUpdateHooks []DistanceDatumHook
var distanceDatumAfterUpdateMu sync.Mutex
var distanceDatumAfterUpdateHooks []DistanceDatumHook

var distanceDatumBeforeDeleteMu sync.Mutex
var distanceDatumBeforeDeleteHooks []DistanceDatumHook
var distanceDatumAfterDeleteMu sync.Mutex
var distanceDatumAfterDeleteHooks []DistanceDatumHook

var distanceDatumBeforeUpsertMu sync.Mutex
var distanceDatumBeforeUpsertHooks []DistanceDatumHook
var distanceDatumAfterUpsertMu sync.Mutex
var distanceDatumAfterUpsertHooks []DistanceDatumHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *DistanceDatum) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range distanceDatumAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *DistanceDatum) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range distanceDatumBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *DistanceDatum) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range distanceDatumAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *DistanceDatum) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range distanceDatumBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *DistanceDatum) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range distanceDatumAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *DistanceDatum) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range distanceDatumBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *DistanceDatum) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range distanceDatumAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *DistanceDatum) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range distanceDatumBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *DistanceDatum) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range distanceDatumAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddDistanceDatumHook registers your hook function for all future operations.
func AddDistanceDatumHook(hookPoint boil.HookPoint, distanceDatumHook DistanceDatumHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		distanceDatumAfterSelectMu.Lock()
		distanceDatumAfterSelectHooks = append(distanceDatumAfterSelectHooks, distanceDatumHook)
		distanceDatumAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		distanceDatumBeforeInsertMu.Lock()
		distanceDatumBeforeInsertHooks = append(distanceDatumBeforeInsertHooks, distanceDatumHook)
		distanceDatumBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		distanceDatumAfterInsertMu.Lock()
		distanceDatumAfterInsertHooks = append(distanceDatumAfterInsertHooks, distanceDatumHook)
		distanceDatumAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		distanceDatumBeforeUpdateMu.Lock()
		distanceDatumBeforeUpdateHooks = append(distanceDatumBeforeUpdateHooks, distanceDatumHook)
		distanceDatumBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		distanceDatumAfterUpdateMu.Lock()
		distanceDatumAfterUpdateHooks = append(distanceDatumAfterUpdateHooks, distanceDatumHook)
		distanceDatumAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		distanceDatumBeforeDeleteMu.Lock()
		distanceDatumBeforeDeleteHooks = append(distanceDatumBeforeDeleteHooks, distanceDatumHook)
		distanceDatumBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		distanceDatumAfterDeleteMu.Lock()
		distanceDatumAfterDeleteHooks = append(distanceDatumAfterDeleteHooks, distanceDatumHook)
		distanceDatumAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		distanceDatumBeforeUpsertMu.Lock()
		distanceDatumBeforeUpsertHooks = append(distanceDatumBeforeUpsertHooks, distanceDatumHook)
		distanceDatumBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		distanceDatumAfterUpsertMu.Lock()
		distanceDatumAfterUpsertHooks = append(distanceDatumAfterUpsertHooks, distanceDatumHook)
		distanceDatumAfterUpsertMu.Unlock()
	}
}

// One returns a single distanceDatum record from the query.
func (q distanceDatumQuery) One(ctx context.Context, exec boil.ContextExecutor) (*DistanceDatum, error) {
	o := &DistanceDatum{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for distance_data")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all DistanceDatum records from the query.
func (q distanceDatumQuery) All(ctx context.Context, exec boil.ContextExecutor) (DistanceDatumSlice, error) {
	var o []*DistanceDatum

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to DistanceDatum slice")
	}

	if len(distanceDatumAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all DistanceDatum records in the query.
func (q distanceDatumQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count distance_data rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q distanceDatumQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if distance_data exists")
	}

	return count > 0, nil
}

// DatumDistanceAlerts retrieves all the distance_alert's DistanceAlerts with an executor via data_id column.
func (o *DistanceDatum) DatumDistanceAlerts(mods ...qm.QueryMod) distanceAlertQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"distance_alerts\".\"data_id\"=?", o.ID),
	)

	return DistanceAlerts(queryMods...)
}

// LoadDatumDistanceAlerts allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (distanceDatumL) LoadDatumDistanceAlerts(ctx context.Context, e boil.ContextExecutor, singular bool, maybeDistanceDatum interface{}, mods queries.Applicator) error {
	var slice []*DistanceDatum
	var object *DistanceDatum

	if singular {
		var ok bool
		object, ok = maybeDistanceDatum.(*DistanceDatum)
		if !ok {
			object = new(DistanceDatum)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeDistanceDatum)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeDistanceDatum))
			}
		}
	} else {
		s, ok := maybeDistanceDatum.(*[]*DistanceDatum)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeDistanceDatum)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeDistanceDatum))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &distanceDatumR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &distanceDatumR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`distance_alerts`),
		qm.WhereIn(`distance_alerts.data_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load distance_alerts")
	}

	var resultSlice []*DistanceAlert
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice distance_alerts")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on distance_alerts")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for distance_alerts")
	}

	if len(distanceAlertAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.DatumDistanceAlerts = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &distanceAlertR{}
			}
			foreign.R.Datum = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.ID, foreign.DataID) {
				local.R.DatumDistanceAlerts = append(local.R.DatumDistanceAlerts, foreign)
				if foreign.R == nil {
					foreign.R = &distanceAlertR{}
				}
				foreign.R.Datum = local
				break
			}
		}
	}

	return nil
}

// AddDatumDistanceAlerts adds the given related objects to the existing relationships
// of the distance_datum, optionally inserting them as new records.
// Appends related to o.R.DatumDistanceAlerts.
// Sets related.R.Datum appropriately.
func (o *DistanceDatum) AddDatumDistanceAlerts(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*DistanceAlert) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.DataID, o.ID)
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"distance_alerts\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"data_id"}),
				strmangle.WhereClause("\"", "\"", 2, distanceAlertPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.DataID, o.ID)
		}
	}

	if o.R == nil {
		o.R = &distanceDatumR{
			DatumDistanceAlerts: related,
		}
	} else {
		o.R.DatumDistanceAlerts = append(o.R.DatumDistanceAlerts, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &distanceAlertR{
				Datum: o,
			}
		} else {
			rel.R.Datum = o
		}
	}
	return nil
}

// SetDatumDistanceAlerts removes all previously related items of the
// distance_datum replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.Datum's DatumDistanceAlerts accordingly.
// Replaces o.R.DatumDistanceAlerts with related.
// Sets related.R.Datum's DatumDistanceAlerts accordingly.
func (o *DistanceDatum) SetDatumDistanceAlerts(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*DistanceAlert) error {
	query := "update \"distance_alerts\" set \"data_id\" = null where \"data_id\" = $1"
	values := []interface{}{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.DatumDistanceAlerts {
			queries.SetScanner(&rel.DataID, nil)
			if rel.R == nil {
				continue
			}

			rel.R.Datum = nil
		}
		o.R.DatumDistanceAlerts = nil
	}

	return o.AddDatumDistanceAlerts(ctx, exec, insert, related...)
}

// RemoveDatumDistanceAlerts relationships from objects passed in.
// Removes related items from R.DatumDistanceAlerts (uses pointer comparison, removal does not keep order)
// Sets related.R.Datum.
func (o *DistanceDatum) RemoveDatumDistanceAlerts(ctx context.Context, exec boil.ContextExecutor, related ...*DistanceAlert) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.DataID, nil)
		if rel.R != nil {
			rel.R.Datum = nil
		}
		if _, err = rel.Update(ctx, exec, boil.Whitelist("data_id")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.DatumDistanceAlerts {
			if rel != ri {
				continue
			}

			ln := len(o.R.DatumDistanceAlerts)
			if ln > 1 && i < ln-1 {
				o.R.DatumDistanceAlerts[i] = o.R.DatumDistanceAlerts[ln-1]
			}
			o.R.DatumDistanceAlerts = o.R.DatumDistanceAlerts[:ln-1]
			break
		}
	}

	return nil
}

// DistanceData retrieves all the records using an executor.
func DistanceData(mods ...qm.QueryMod) distanceDatumQuery {
	mods = append(mods, qm.From("\"distance_data\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"distance_data\".*"})
	}

	return distanceDatumQuery{q}
}

// FindDistanceDatum retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindDistanceDatum(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*DistanceDatum, error) {
	distanceDatumObj := &DistanceDatum{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"distance_data\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, distanceDatumObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from distance_data")
	}

	if err = distanceDatumObj.doAfterSelectHooks(ctx, exec); err != nil {
		return distanceDatumObj, err
	}

	return distanceDatumObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *DistanceDatum) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no distance_data provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(distanceDatumColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	distanceDatumInsertCacheMut.RLock()
	cache, cached := distanceDatumInsertCache[key]
	distanceDatumInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			distanceDatumAllColumns,
			distanceDatumColumnsWithDefault,
			distanceDatumColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(distanceDatumType, distanceDatumMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(distanceDatumType, distanceDatumMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"distance_data\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"distance_data\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into distance_data")
	}

	if !cached {
		distanceDatumInsertCacheMut.Lock()
		distanceDatumInsertCache[key] = cache
		distanceDatumInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the DistanceDatum.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *DistanceDatum) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	distanceDatumUpdateCacheMut.RLock()
	cache, cached := distanceDatumUpdateCache[key]
	distanceDatumUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			distanceDatumAllColumns,
			distanceDatumPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update distance_data, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"distance_data\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, distanceDatumPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(distanceDatumType, distanceDatumMapping, append(wl, distanceDatumPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update distance_data row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for distance_data")
	}

	if !cached {
		distanceDatumUpdateCacheMut.Lock()
		distanceDatumUpdateCache[key] = cache
		distanceDatumUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q distanceDatumQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for distance_data")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for distance_data")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o DistanceDatumSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), distanceDatumPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"distance_data\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, distanceDatumPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in distanceDatum slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all distanceDatum")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *DistanceDatum) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no distance_data provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(distanceDatumColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	distanceDatumUpsertCacheMut.RLock()
	cache, cached := distanceDatumUpsertCache[key]
	distanceDatumUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			distanceDatumAllColumns,
			distanceDatumColumnsWithDefault,
			distanceDatumColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			distanceDatumAllColumns,
			distanceDatumPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert distance_data, could not build update column list")
		}

		ret := strmangle.SetComplement(distanceDatumAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(distanceDatumPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert distance_data, could not build conflict column list")
			}

			conflict = make([]string, len(distanceDatumPrimaryKeyColumns))
			copy(conflict, distanceDatumPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"distance_data\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(distanceDatumType, distanceDatumMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(distanceDatumType, distanceDatumMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert distance_data")
	}

	if !cached {
		distanceDatumUpsertCacheMut.Lock()
		distanceDatumUpsertCache[key] = cache
		distanceDatumUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single DistanceDatum record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *DistanceDatum) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no DistanceDatum provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), distanceDatumPrimaryKeyMapping)
	sql := "DELETE FROM \"distance_data\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from distance_data")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for distance_data")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q distanceDatumQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no distanceDatumQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from distance_data")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for distance_data")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o DistanceDatumSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(distanceDatumBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), distanceDatumPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"distance_data\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, distanceDatumPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from distanceDatum slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for distance_data")
	}

	if len(distanceDatumAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *DistanceDatum) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindDistanceDatum(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *DistanceDatumSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := DistanceDatumSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), distanceDatumPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"distance_data\".* FROM \"distance_data\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, distanceDatumPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in DistanceDatumSlice")
	}

	*o = slice

	return nil
}

// DistanceDatumExists checks if the DistanceDatum row exists.
func DistanceDatumExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"distance_data\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if distance_data exists")
	}

	return exists, nil
}

// Exists checks if the DistanceDatum row exists.
func (o *DistanceDatum) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return DistanceDatumExists(ctx, exec, o.ID)
}
