// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testDistanceAlerts(t *testing.T) {
	t.Parallel()

	query := DistanceAlerts()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testDistanceAlertsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DistanceAlert{}
	if err = randomize.Struct(seed, o, distanceAlertDBTypes, true, distanceAlertColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DistanceAlert struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := DistanceAlerts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testDistanceAlertsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DistanceAlert{}
	if err = randomize.Struct(seed, o, distanceAlertDBTypes, true, distanceAlertColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DistanceAlert struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := DistanceAlerts().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := DistanceAlerts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testDistanceAlertsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DistanceAlert{}
	if err = randomize.Struct(seed, o, distanceAlertDBTypes, true, distanceAlertColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DistanceAlert struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := DistanceAlertSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := DistanceAlerts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testDistanceAlertsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DistanceAlert{}
	if err = randomize.Struct(seed, o, distanceAlertDBTypes, true, distanceAlertColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DistanceAlert struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := DistanceAlertExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if DistanceAlert exists: %s", err)
	}
	if !e {
		t.Errorf("Expected DistanceAlertExists to return true, but got false.")
	}
}

func testDistanceAlertsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DistanceAlert{}
	if err = randomize.Struct(seed, o, distanceAlertDBTypes, true, distanceAlertColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DistanceAlert struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	distanceAlertFound, err := FindDistanceAlert(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if distanceAlertFound == nil {
		t.Error("want a record, got nil")
	}
}

func testDistanceAlertsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DistanceAlert{}
	if err = randomize.Struct(seed, o, distanceAlertDBTypes, true, distanceAlertColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DistanceAlert struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = DistanceAlerts().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testDistanceAlertsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DistanceAlert{}
	if err = randomize.Struct(seed, o, distanceAlertDBTypes, true, distanceAlertColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DistanceAlert struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := DistanceAlerts().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testDistanceAlertsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	distanceAlertOne := &DistanceAlert{}
	distanceAlertTwo := &DistanceAlert{}
	if err = randomize.Struct(seed, distanceAlertOne, distanceAlertDBTypes, false, distanceAlertColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DistanceAlert struct: %s", err)
	}
	if err = randomize.Struct(seed, distanceAlertTwo, distanceAlertDBTypes, false, distanceAlertColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DistanceAlert struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = distanceAlertOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = distanceAlertTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := DistanceAlerts().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testDistanceAlertsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	distanceAlertOne := &DistanceAlert{}
	distanceAlertTwo := &DistanceAlert{}
	if err = randomize.Struct(seed, distanceAlertOne, distanceAlertDBTypes, false, distanceAlertColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DistanceAlert struct: %s", err)
	}
	if err = randomize.Struct(seed, distanceAlertTwo, distanceAlertDBTypes, false, distanceAlertColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DistanceAlert struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = distanceAlertOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = distanceAlertTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := DistanceAlerts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func distanceAlertBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *DistanceAlert) error {
	*o = DistanceAlert{}
	return nil
}

func distanceAlertAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *DistanceAlert) error {
	*o = DistanceAlert{}
	return nil
}

func distanceAlertAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *DistanceAlert) error {
	*o = DistanceAlert{}
	return nil
}

func distanceAlertBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *DistanceAlert) error {
	*o = DistanceAlert{}
	return nil
}

func distanceAlertAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *DistanceAlert) error {
	*o = DistanceAlert{}
	return nil
}

func distanceAlertBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *DistanceAlert) error {
	*o = DistanceAlert{}
	return nil
}

func distanceAlertAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *DistanceAlert) error {
	*o = DistanceAlert{}
	return nil
}

func distanceAlertBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *DistanceAlert) error {
	*o = DistanceAlert{}
	return nil
}

func distanceAlertAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *DistanceAlert) error {
	*o = DistanceAlert{}
	return nil
}

func testDistanceAlertsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &DistanceAlert{}
	o := &DistanceAlert{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, distanceAlertDBTypes, false); err != nil {
		t.Errorf("Unable to randomize DistanceAlert object: %s", err)
	}

	AddDistanceAlertHook(boil.BeforeInsertHook, distanceAlertBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	distanceAlertBeforeInsertHooks = []DistanceAlertHook{}

	AddDistanceAlertHook(boil.AfterInsertHook, distanceAlertAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	distanceAlertAfterInsertHooks = []DistanceAlertHook{}

	AddDistanceAlertHook(boil.AfterSelectHook, distanceAlertAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	distanceAlertAfterSelectHooks = []DistanceAlertHook{}

	AddDistanceAlertHook(boil.BeforeUpdateHook, distanceAlertBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	distanceAlertBeforeUpdateHooks = []DistanceAlertHook{}

	AddDistanceAlertHook(boil.AfterUpdateHook, distanceAlertAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	distanceAlertAfterUpdateHooks = []DistanceAlertHook{}

	AddDistanceAlertHook(boil.BeforeDeleteHook, distanceAlertBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	distanceAlertBeforeDeleteHooks = []DistanceAlertHook{}

	AddDistanceAlertHook(boil.AfterDeleteHook, distanceAlertAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	distanceAlertAfterDeleteHooks = []DistanceAlertHook{}

	AddDistanceAlertHook(boil.BeforeUpsertHook, distanceAlertBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	distanceAlertBeforeUpsertHooks = []DistanceAlertHook{}

	AddDistanceAlertHook(boil.AfterUpsertHook, distanceAlertAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	distanceAlertAfterUpsertHooks = []DistanceAlertHook{}
}

func testDistanceAlertsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DistanceAlert{}
	if err = randomize.Struct(seed, o, distanceAlertDBTypes, true, distanceAlertColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DistanceAlert struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := DistanceAlerts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testDistanceAlertsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DistanceAlert{}
	if err = randomize.Struct(seed, o, distanceAlertDBTypes, true); err != nil {
		t.Errorf("Unable to randomize DistanceAlert struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(distanceAlertColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := DistanceAlerts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testDistanceAlertToOneDistanceDatumUsingDatum(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local DistanceAlert
	var foreign DistanceDatum

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, distanceAlertDBTypes, true, distanceAlertColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DistanceAlert struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, distanceDatumDBTypes, false, distanceDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DistanceDatum struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&local.DataID, foreign.ID)
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Datum().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if !queries.Equal(check.ID, foreign.ID) {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	ranAfterSelectHook := false
	AddDistanceDatumHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *DistanceDatum) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := DistanceAlertSlice{&local}
	if err = local.L.LoadDatum(ctx, tx, false, (*[]*DistanceAlert)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Datum == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Datum = nil
	if err = local.L.LoadDatum(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Datum == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testDistanceAlertToOneSetOpDistanceDatumUsingDatum(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a DistanceAlert
	var b, c DistanceDatum

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, distanceAlertDBTypes, false, strmangle.SetComplement(distanceAlertPrimaryKeyColumns, distanceAlertColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, distanceDatumDBTypes, false, strmangle.SetComplement(distanceDatumPrimaryKeyColumns, distanceDatumColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, distanceDatumDBTypes, false, strmangle.SetComplement(distanceDatumPrimaryKeyColumns, distanceDatumColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*DistanceDatum{&b, &c} {
		err = a.SetDatum(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Datum != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.DatumDistanceAlerts[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if !queries.Equal(a.DataID, x.ID) {
			t.Error("foreign key was wrong value", a.DataID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.DataID))
		reflect.Indirect(reflect.ValueOf(&a.DataID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if !queries.Equal(a.DataID, x.ID) {
			t.Error("foreign key was wrong value", a.DataID, x.ID)
		}
	}
}

func testDistanceAlertToOneRemoveOpDistanceDatumUsingDatum(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a DistanceAlert
	var b DistanceDatum

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, distanceAlertDBTypes, false, strmangle.SetComplement(distanceAlertPrimaryKeyColumns, distanceAlertColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, distanceDatumDBTypes, false, strmangle.SetComplement(distanceDatumPrimaryKeyColumns, distanceDatumColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = a.SetDatum(ctx, tx, true, &b); err != nil {
		t.Fatal(err)
	}

	if err = a.RemoveDatum(ctx, tx, &b); err != nil {
		t.Error("failed to remove relationship")
	}

	count, err := a.Datum().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 0 {
		t.Error("want no relationships remaining")
	}

	if a.R.Datum != nil {
		t.Error("R struct entry should be nil")
	}

	if !queries.IsValuerNil(a.DataID) {
		t.Error("foreign key value should be nil")
	}

	if len(b.R.DatumDistanceAlerts) != 0 {
		t.Error("failed to remove a from b's relationships")
	}
}

func testDistanceAlertsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DistanceAlert{}
	if err = randomize.Struct(seed, o, distanceAlertDBTypes, true, distanceAlertColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DistanceAlert struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testDistanceAlertsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DistanceAlert{}
	if err = randomize.Struct(seed, o, distanceAlertDBTypes, true, distanceAlertColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DistanceAlert struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := DistanceAlertSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testDistanceAlertsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &DistanceAlert{}
	if err = randomize.Struct(seed, o, distanceAlertDBTypes, true, distanceAlertColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DistanceAlert struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := DistanceAlerts().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	distanceAlertDBTypes = map[string]string{`ID`: `bigint`, `DeviceID`: `character varying`, `DataID`: `bigint`, `DistanceCM`: `numeric`, `ThresholdType`: `character varying`, `ThresholdValue`: `numeric`, `AlertStatus`: `character varying`, `AcknowledgedAt`: `timestamp without time zone`, `ResolvedAt`: `timestamp without time zone`, `CreatedAt`: `timestamp without time zone`}
	_                    = bytes.MinRead
)

func testDistanceAlertsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(distanceAlertPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(distanceAlertAllColumns) == len(distanceAlertPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &DistanceAlert{}
	if err = randomize.Struct(seed, o, distanceAlertDBTypes, true, distanceAlertColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DistanceAlert struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := DistanceAlerts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, distanceAlertDBTypes, true, distanceAlertPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize DistanceAlert struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testDistanceAlertsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(distanceAlertAllColumns) == len(distanceAlertPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &DistanceAlert{}
	if err = randomize.Struct(seed, o, distanceAlertDBTypes, true, distanceAlertColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize DistanceAlert struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := DistanceAlerts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, distanceAlertDBTypes, true, distanceAlertPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize DistanceAlert struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(distanceAlertAllColumns, distanceAlertPrimaryKeyColumns) {
		fields = distanceAlertAllColumns
	} else {
		fields = strmangle.SetComplement(
			distanceAlertAllColumns,
			distanceAlertPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := DistanceAlertSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testDistanceAlertsUpsert(t *testing.T) {
	t.Parallel()

	if len(distanceAlertAllColumns) == len(distanceAlertPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := DistanceAlert{}
	if err = randomize.Struct(seed, &o, distanceAlertDBTypes, true); err != nil {
		t.Errorf("Unable to randomize DistanceAlert struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert DistanceAlert: %s", err)
	}

	count, err := DistanceAlerts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, distanceAlertDBTypes, false, distanceAlertPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize DistanceAlert struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert DistanceAlert: %s", err)
	}

	count, err = DistanceAlerts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
