// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testMicrophoneData(t *testing.T) {
	t.Parallel()

	query := MicrophoneData()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testMicrophoneDataDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MicrophoneDatum{}
	if err = randomize.Struct(seed, o, microphoneDatumDBTypes, true, microphoneDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MicrophoneDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := MicrophoneData().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testMicrophoneDataQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MicrophoneDatum{}
	if err = randomize.Struct(seed, o, microphoneDatumDBTypes, true, microphoneDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MicrophoneDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := MicrophoneData().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := MicrophoneData().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testMicrophoneDataSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MicrophoneDatum{}
	if err = randomize.Struct(seed, o, microphoneDatumDBTypes, true, microphoneDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MicrophoneDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := MicrophoneDatumSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := MicrophoneData().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testMicrophoneDataExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MicrophoneDatum{}
	if err = randomize.Struct(seed, o, microphoneDatumDBTypes, true, microphoneDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MicrophoneDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := MicrophoneDatumExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if MicrophoneDatum exists: %s", err)
	}
	if !e {
		t.Errorf("Expected MicrophoneDatumExists to return true, but got false.")
	}
}

func testMicrophoneDataFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MicrophoneDatum{}
	if err = randomize.Struct(seed, o, microphoneDatumDBTypes, true, microphoneDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MicrophoneDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	microphoneDatumFound, err := FindMicrophoneDatum(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if microphoneDatumFound == nil {
		t.Error("want a record, got nil")
	}
}

func testMicrophoneDataBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MicrophoneDatum{}
	if err = randomize.Struct(seed, o, microphoneDatumDBTypes, true, microphoneDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MicrophoneDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = MicrophoneData().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testMicrophoneDataOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MicrophoneDatum{}
	if err = randomize.Struct(seed, o, microphoneDatumDBTypes, true, microphoneDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MicrophoneDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := MicrophoneData().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testMicrophoneDataAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	microphoneDatumOne := &MicrophoneDatum{}
	microphoneDatumTwo := &MicrophoneDatum{}
	if err = randomize.Struct(seed, microphoneDatumOne, microphoneDatumDBTypes, false, microphoneDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MicrophoneDatum struct: %s", err)
	}
	if err = randomize.Struct(seed, microphoneDatumTwo, microphoneDatumDBTypes, false, microphoneDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MicrophoneDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = microphoneDatumOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = microphoneDatumTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := MicrophoneData().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testMicrophoneDataCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	microphoneDatumOne := &MicrophoneDatum{}
	microphoneDatumTwo := &MicrophoneDatum{}
	if err = randomize.Struct(seed, microphoneDatumOne, microphoneDatumDBTypes, false, microphoneDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MicrophoneDatum struct: %s", err)
	}
	if err = randomize.Struct(seed, microphoneDatumTwo, microphoneDatumDBTypes, false, microphoneDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MicrophoneDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = microphoneDatumOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = microphoneDatumTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := MicrophoneData().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func microphoneDatumBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *MicrophoneDatum) error {
	*o = MicrophoneDatum{}
	return nil
}

func microphoneDatumAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *MicrophoneDatum) error {
	*o = MicrophoneDatum{}
	return nil
}

func microphoneDatumAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *MicrophoneDatum) error {
	*o = MicrophoneDatum{}
	return nil
}

func microphoneDatumBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *MicrophoneDatum) error {
	*o = MicrophoneDatum{}
	return nil
}

func microphoneDatumAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *MicrophoneDatum) error {
	*o = MicrophoneDatum{}
	return nil
}

func microphoneDatumBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *MicrophoneDatum) error {
	*o = MicrophoneDatum{}
	return nil
}

func microphoneDatumAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *MicrophoneDatum) error {
	*o = MicrophoneDatum{}
	return nil
}

func microphoneDatumBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *MicrophoneDatum) error {
	*o = MicrophoneDatum{}
	return nil
}

func microphoneDatumAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *MicrophoneDatum) error {
	*o = MicrophoneDatum{}
	return nil
}

func testMicrophoneDataHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &MicrophoneDatum{}
	o := &MicrophoneDatum{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, microphoneDatumDBTypes, false); err != nil {
		t.Errorf("Unable to randomize MicrophoneDatum object: %s", err)
	}

	AddMicrophoneDatumHook(boil.BeforeInsertHook, microphoneDatumBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	microphoneDatumBeforeInsertHooks = []MicrophoneDatumHook{}

	AddMicrophoneDatumHook(boil.AfterInsertHook, microphoneDatumAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	microphoneDatumAfterInsertHooks = []MicrophoneDatumHook{}

	AddMicrophoneDatumHook(boil.AfterSelectHook, microphoneDatumAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	microphoneDatumAfterSelectHooks = []MicrophoneDatumHook{}

	AddMicrophoneDatumHook(boil.BeforeUpdateHook, microphoneDatumBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	microphoneDatumBeforeUpdateHooks = []MicrophoneDatumHook{}

	AddMicrophoneDatumHook(boil.AfterUpdateHook, microphoneDatumAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	microphoneDatumAfterUpdateHooks = []MicrophoneDatumHook{}

	AddMicrophoneDatumHook(boil.BeforeDeleteHook, microphoneDatumBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	microphoneDatumBeforeDeleteHooks = []MicrophoneDatumHook{}

	AddMicrophoneDatumHook(boil.AfterDeleteHook, microphoneDatumAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	microphoneDatumAfterDeleteHooks = []MicrophoneDatumHook{}

	AddMicrophoneDatumHook(boil.BeforeUpsertHook, microphoneDatumBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	microphoneDatumBeforeUpsertHooks = []MicrophoneDatumHook{}

	AddMicrophoneDatumHook(boil.AfterUpsertHook, microphoneDatumAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	microphoneDatumAfterUpsertHooks = []MicrophoneDatumHook{}
}

func testMicrophoneDataInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MicrophoneDatum{}
	if err = randomize.Struct(seed, o, microphoneDatumDBTypes, true, microphoneDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MicrophoneDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := MicrophoneData().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testMicrophoneDataInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MicrophoneDatum{}
	if err = randomize.Struct(seed, o, microphoneDatumDBTypes, true); err != nil {
		t.Errorf("Unable to randomize MicrophoneDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(microphoneDatumColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := MicrophoneData().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testMicrophoneDatumToManyDatumMicrophoneAlerts(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a MicrophoneDatum
	var b, c MicrophoneAlert

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, microphoneDatumDBTypes, true, microphoneDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MicrophoneDatum struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, microphoneAlertDBTypes, false, microphoneAlertColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, microphoneAlertDBTypes, false, microphoneAlertColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&b.DataID, a.ID)
	queries.Assign(&c.DataID, a.ID)
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.DatumMicrophoneAlerts().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if queries.Equal(v.DataID, b.DataID) {
			bFound = true
		}
		if queries.Equal(v.DataID, c.DataID) {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := MicrophoneDatumSlice{&a}
	if err = a.L.LoadDatumMicrophoneAlerts(ctx, tx, false, (*[]*MicrophoneDatum)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.DatumMicrophoneAlerts); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.DatumMicrophoneAlerts = nil
	if err = a.L.LoadDatumMicrophoneAlerts(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.DatumMicrophoneAlerts); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testMicrophoneDatumToManyAddOpDatumMicrophoneAlerts(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a MicrophoneDatum
	var b, c, d, e MicrophoneAlert

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, microphoneDatumDBTypes, false, strmangle.SetComplement(microphoneDatumPrimaryKeyColumns, microphoneDatumColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*MicrophoneAlert{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, microphoneAlertDBTypes, false, strmangle.SetComplement(microphoneAlertPrimaryKeyColumns, microphoneAlertColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*MicrophoneAlert{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddDatumMicrophoneAlerts(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if !queries.Equal(a.ID, first.DataID) {
			t.Error("foreign key was wrong value", a.ID, first.DataID)
		}
		if !queries.Equal(a.ID, second.DataID) {
			t.Error("foreign key was wrong value", a.ID, second.DataID)
		}

		if first.R.Datum != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.Datum != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.DatumMicrophoneAlerts[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.DatumMicrophoneAlerts[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.DatumMicrophoneAlerts().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testMicrophoneDatumToManySetOpDatumMicrophoneAlerts(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a MicrophoneDatum
	var b, c, d, e MicrophoneAlert

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, microphoneDatumDBTypes, false, strmangle.SetComplement(microphoneDatumPrimaryKeyColumns, microphoneDatumColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*MicrophoneAlert{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, microphoneAlertDBTypes, false, strmangle.SetComplement(microphoneAlertPrimaryKeyColumns, microphoneAlertColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.SetDatumMicrophoneAlerts(ctx, tx, false, &b, &c)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.DatumMicrophoneAlerts().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	err = a.SetDatumMicrophoneAlerts(ctx, tx, true, &d, &e)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.DatumMicrophoneAlerts().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.DataID) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.DataID) {
		t.Error("want c's foreign key value to be nil")
	}
	if !queries.Equal(a.ID, d.DataID) {
		t.Error("foreign key was wrong value", a.ID, d.DataID)
	}
	if !queries.Equal(a.ID, e.DataID) {
		t.Error("foreign key was wrong value", a.ID, e.DataID)
	}

	if b.R.Datum != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.Datum != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.Datum != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}
	if e.R.Datum != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}

	if a.R.DatumMicrophoneAlerts[0] != &d {
		t.Error("relationship struct slice not set to correct value")
	}
	if a.R.DatumMicrophoneAlerts[1] != &e {
		t.Error("relationship struct slice not set to correct value")
	}
}

func testMicrophoneDatumToManyRemoveOpDatumMicrophoneAlerts(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a MicrophoneDatum
	var b, c, d, e MicrophoneAlert

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, microphoneDatumDBTypes, false, strmangle.SetComplement(microphoneDatumPrimaryKeyColumns, microphoneDatumColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*MicrophoneAlert{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, microphoneAlertDBTypes, false, strmangle.SetComplement(microphoneAlertPrimaryKeyColumns, microphoneAlertColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.AddDatumMicrophoneAlerts(ctx, tx, true, foreigners...)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.DatumMicrophoneAlerts().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 4 {
		t.Error("count was wrong:", count)
	}

	err = a.RemoveDatumMicrophoneAlerts(ctx, tx, foreigners[:2]...)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.DatumMicrophoneAlerts().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.DataID) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.DataID) {
		t.Error("want c's foreign key value to be nil")
	}

	if b.R.Datum != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.Datum != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.Datum != &a {
		t.Error("relationship to a should have been preserved")
	}
	if e.R.Datum != &a {
		t.Error("relationship to a should have been preserved")
	}

	if len(a.R.DatumMicrophoneAlerts) != 2 {
		t.Error("should have preserved two relationships")
	}

	// Removal doesn't do a stable deletion for performance so we have to flip the order
	if a.R.DatumMicrophoneAlerts[1] != &d {
		t.Error("relationship to d should have been preserved")
	}
	if a.R.DatumMicrophoneAlerts[0] != &e {
		t.Error("relationship to e should have been preserved")
	}
}

func testMicrophoneDataReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MicrophoneDatum{}
	if err = randomize.Struct(seed, o, microphoneDatumDBTypes, true, microphoneDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MicrophoneDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testMicrophoneDataReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MicrophoneDatum{}
	if err = randomize.Struct(seed, o, microphoneDatumDBTypes, true, microphoneDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MicrophoneDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := MicrophoneDatumSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testMicrophoneDataSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MicrophoneDatum{}
	if err = randomize.Struct(seed, o, microphoneDatumDBTypes, true, microphoneDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MicrophoneDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := MicrophoneData().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	microphoneDatumDBTypes = map[string]string{`ID`: `bigint`, `DeviceID`: `character varying`, `Decibels`: `numeric`, `RecordedAt`: `timestamp without time zone`}
	_                      = bytes.MinRead
)

func testMicrophoneDataUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(microphoneDatumPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(microphoneDatumAllColumns) == len(microphoneDatumPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &MicrophoneDatum{}
	if err = randomize.Struct(seed, o, microphoneDatumDBTypes, true, microphoneDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MicrophoneDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := MicrophoneData().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, microphoneDatumDBTypes, true, microphoneDatumPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize MicrophoneDatum struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testMicrophoneDataSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(microphoneDatumAllColumns) == len(microphoneDatumPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &MicrophoneDatum{}
	if err = randomize.Struct(seed, o, microphoneDatumDBTypes, true, microphoneDatumColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MicrophoneDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := MicrophoneData().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, microphoneDatumDBTypes, true, microphoneDatumPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize MicrophoneDatum struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(microphoneDatumAllColumns, microphoneDatumPrimaryKeyColumns) {
		fields = microphoneDatumAllColumns
	} else {
		fields = strmangle.SetComplement(
			microphoneDatumAllColumns,
			microphoneDatumPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := MicrophoneDatumSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testMicrophoneDataUpsert(t *testing.T) {
	t.Parallel()

	if len(microphoneDatumAllColumns) == len(microphoneDatumPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := MicrophoneDatum{}
	if err = randomize.Struct(seed, &o, microphoneDatumDBTypes, true); err != nil {
		t.Errorf("Unable to randomize MicrophoneDatum struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert MicrophoneDatum: %s", err)
	}

	count, err := MicrophoneData().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, microphoneDatumDBTypes, false, microphoneDatumPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize MicrophoneDatum struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert MicrophoneDatum: %s", err)
	}

	count, err = MicrophoneData().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
